### ISSUE TITLE
System reporting as HS but is LS

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#109]
Ayeroilen (system sec status 0.49) is being rounded up it to 0.5 in pathfinder and showing as High Sec and not Low Sec. http://i.imgur.com/DvMwxhy.png screen shot of values.

**Comment by exodus4d** [comment]
Thanks for reporting!

- TrueSec rounding is now removed from DB query and moved into `ccpsystemsmapper.php`.

This will be fixed with the upcoming release.

**Comment by Tupsi** [comment]
This is now fixed in the map, but (still) broken in the Routes table. Low Sec systems like Aunenen show up with orange L in the map, but with a yellow system icon in the route. The average function seems to use the correct number though, as Jita route with any wh exit using Aunenen shows up with an orange 0.44, although the whole way has only yellows, greens and blues listed with first being a yellow Aunenen as mentioned above (which is wrong). So this is not yet fully fixed.

**Comment by Tupsi** [comment]
I just got a report yesterday that this is still a thing in the routes table, so please reinvestigate. Aunenen for instance still gets a yellow dot although it is a lowsec.

**Comment by exodus4d** [comment]
This is now fixed with the upcoming release. If you have a private installation running, You should (re)build your *index*. 
Check #125 for more information about that.
