### ISSUE TITLE
Feature Request: Jump Log

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#113]
I would be nice to have a log of who jumped a wh connection with what type of ship and a mass sum to get a rough idea of what went through. I am fully aware of the fact that it can only be very rough, as you have no means to track if the ship used active mwd, plates etc. So one could only add up basic hulls and only if the person has pathfinder open while doing the jump, but still its a nice help on what to bring when rolling.

**Comment by exodus4d** [comment]
Yeah, This feature is on my "TODO" list :)

The first "preparations" for a *Jump Log* are already done. The pilot location (system) update is now handled by *CCPs CREST API* (with the upcoming `v1.0.0.RC3` release). 
This allows me, to track pilots/ships which are currently not having *Pathfinder* open.
This should make a further implementation much more efficient, because it does not rely on characters using the IGB.

**Comment by exodus4d** [comment]
This can no longer be implemented... :(
See: #264
