### ISSUE TITLE
PHP 5.5 compatibility

### ISSUE THREAD

**Issue by kiu** [exodus4d/pathfinder#118]
It seems pathfinder started to use PHP language features (like arrays as const, thats why /setup crashes for me) introduced in PHP 5.6. Unfortunately Ubuntu 14.04 LTS which is widely in use today and supported till mid-2019 only offers 5.5 support out of the box.

Wondering if lots of code is dependent on 5.6 and if a refactoring for the sake of providing an easier self hosting is on the table?

**Comment by Zumochi** [comment]
It might be easier for you to use [backports](https://help.ubuntu.com/community/UbuntuBackports), I don't know if the dev is planning on lowering requirements...

**Comment by exodus4d** [comment]
@kiu Unfortunately there are no plans to make *Pathfinder* backwards compatible to any PHP version < `v.5.6` (please check the [(wiki) - Requirements](https://github.com/exodus4d/pathfinder/wiki/Requirements) page for more information).

The reason is simple: I don´t have the time for testing any feature on a large variety of PHP versions :(
I switched my *local development*  and *production* environment to PHP `v.7.x` (3 month ago), but there is also a `v.5.6` *integration* server for testing features.
