### ISSUE TITLE
Animations when switching maps hinder usability

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#120]
The animations that occur when switching between maps massively hinder usability; changing a map takes up to 2-3 seconds on large maps and is frustrating for users.

**Comment by exodus4d** [comment]
Thanks for reporting, sorry for the late response (I was busy with the new CREST login process, coming in the next release)

Loading animation was removed for larger maps (> 20 systems). This was just an issue when using desktop browsers. Animations where already disabled when using IGB (because of its slow/deprecated javascript engine).

**Comment by atkinsj** [comment]
Thanks mate, I really appreciate it.

Personally I'll be disabling it for all maps on our local fork -- the feedback we've had from an overwhelming number of our users is that the Pathfinder animations feel 'overdone' and really do hinder usability. People are looking for something quick and performant out of this tool and at the moment it feels like the focus is on new technologies and looking snazzy than usability.

Just my 0.02c. Thanks again for all the work you do on this though I really do appreciate it and look forward to using it going forward!
