### ISSUE TITLE
SSO re-prompts for application permissions on every login

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#128]
The new SSO implementation in the develop branch prompts the user to grant authorisation on every login event. This only needs to happen once; when you successfully get granted permission you can use the authorization token to [grant new refresh tokens](https://eveonline-third-party-documentation.readthedocs.org/en/latest/sso/refreshtokens.html).

If the user wants to remove Pathfinder's access via SSO they can do so in their account management.

**Comment by exodus4d** [comment]
@atkinsj Yeah thats right. 

Since a `access_token` expires after 20min, new `access_token`´s are requested automatically 2min before they expire by the characters `request_token` (which has no expire time). So the basic logic is already implemented and used for any API Call:[charactermodel.php#L237](https://github.com/exodus4d/pathfinder/blob/develop/app/main/model/charactermodel.php#L237)


Nevertheless, I need the SSO-Login for now. I have to figure out, which maps should be shown to the current user. If you have multiple Acc with multiple characters, I need to know which characters maps should be shown.
If you switch characters, different maps should be visible. I don´t want relay on any Client-Site (Cookie) storage for those information. The current character is SESSION stored.

Any ideas to improve this?

**Comment by atkinsj** [comment]
I don't think the trade off for what you're trying to achieve is there. The
goal for a wormhole tracking application should always be ease of use for
the scouts: anything that slows or hinders them should be avoided at all
costs.

You could use client side cookie storage and set one per logged in
character. When they login they get promoted for which character they want
to use for that session -- provide them the ability to set a default and
disable the prompt. Allow users to swap between characters in the GUI.

You probably want a way of linking characters if you take this approach but
you COULD do it all from client side cookies.

**Comment by exodus4d** [comment]
![character switch](https://cloud.githubusercontent.com/assets/9299033/14589001/d0a09a58-04d7-11e6-864e-eb4fe6054e92.png)

- The character linking is already done (and working in `develop` branch. Multiple **characters** can be linked to one **user**. 
- characters will be removed from a **user** in case the `CharacterOwnerHash` has changed [CREST docu "Obtaining Character ID"](https://eveonline-third-party-documentation.readthedocs.org/en/latest/sso/obtaincharacterid.html)

Yeah Ill probably move the current logged in character to cookies and validate them on Server-Side on any request. The whole CREST-SSO stuff becomes a lot more complicated than I could image .  :(
I have to check for security issues when moving information to the client. But at the end, your are right with your "keep it simple" idea. ;)

**Comment by atkinsj** [comment]
Oh sweet, I missed that. There are good documented ways to do secure client
side cookie storage for tokens; let me know if you need any/advice help.

Givdn that you've done the hard work linking characters and users I think
your best bet is to store a single session cookie for the user--independent
of any of the CREST SSO, a pure Pathfinder session id--and authenticate on
that when the user hits the appcontroller.

Let me know if you need any advice as I've done this in the last or can at
least point you to some good resources.

**Comment by exodus4d** [comment]
Let us close this one, It is more or less a duplicate. #138.is much more documented and includes all the commits.
