### ISSUE TITLE
[Feature Request] Ability to turn off gate tracking permanently

### ISSUE THREAD

**Issue by Bingmano** [exodus4d/pathfinder#132]
While i appreciate the ability to track K-Space gates as a pilot jumps, it becomes cumbersome if a pilot forgets to turn off the track me slider.  Once they turn it off, they forget to turn it back on.  Could there be a setting that defaults to turn off K-Space tracking and keep W-Space on?

I guess what i'm looking for is greater flexibility on what is tracked.  An idea could be to make it map specific (i.e. a corp chain map could be controlled by directors/CEO on what kind of jumps are tracked).

**Comment by exodus4d** [comment]
Yeah this feature is on my "TODO" list for a long time now :( But it is definitely coming in the near future. 

I haven´t thought out, how to to implement it:
- "Map specific" sounds valid. Restrict options to some characters (e.g. directors/CEO) will require an additional layer of "access roles" and is more complex to implement
- "Character specific" is much easier to implement (like the existing "map share settings")

This feature will probably come in line with #117

**Comment by atkinsj** [comment]
The approach we have taken with this is a modification to prevent automatic
addition of multiple k-space hops.

If you exit a WH then that k-space system is added but if for example you
leave tracking on and jump all the way to Jita, you don't get another 20
k-space systems on the map. This was very very heavily requested by our
scouts and mirrors the Siggy model.

**Comment by Tupsi** [comment]
I would really love to see this implemented as @atkinsj did it. How about you share your modification with us and make a pull request for your changes?

**Comment by atkinsj** [comment]
I'll take a look at cleaning it up and getting a PR in. It's a pretty trivial change from memory but I'll go find the commit and make sure (our fork is pretty unique unfortunately).

The way we do it is if you make 2 k-space jumps in a row, that are connected by gates, then tracking is automatically disabled. This keeps tracking enabled if for example you find a chain that is k-space -> k-space -> k-space (since that is still valid).

**Comment by Calavoow** [comment]
@atkinsj I suppose you mean k-space -> k-space -> j-space? I think it would be better to just leave it to manual adding. Where a k-space -> j-space will simply generate a new chain and adding a k-space->k-space connection manually is the solution. To me it seems arbitrary where the number of k-space jumps should be limited because 3x k-space -> j-space is still "valid", or for any constant `i times k-space` really.

We're also looking forward to such a feature in my corp!

**Comment by atkinsj** [comment]
It's 3 k-space systems that are connected by gates, not any 3 k space
systems. If that happens then we disable tracking and the user can manually
flip it back on or add the connection.

**Comment by Calavoow** [comment]
Does that mean the k-spaces appear on the map? Or only once a wh connection is used? If the latter, then it could be fine, otherwise it creates unnecessary clutter.

**Comment by exodus4d** [comment]
OK, here are my ideas for this feature:

* We bind the "map tracking" behaviour to the `map scope`. There is already a `map scope` dropdown available in the "Create new map" dialog. There is just a single option "wormhole" available and it is more or less useless. 
 * we add new options like "k-space", "jumpbridges",... to it
* When a new system jump is detected, *Pathfinder* checks the `map scope` of the current map and decides what should be done.
- We leave the current "map tracking" toggle button at it is. I don´t want to force clients to add new systems, if they want to.

##### Scope "wormhole":

- k-space to k-space jumps are **not** tracked. w-space to w-space are tracked, w-space to k-space will add the target system, k-space to w-space will add both systems (like *Siggy*)

##### Scope "k-space"

- k-space to k-space is tracked, w-space to w-space is **not**, w-space to k-space adds both systems, k-space to w-space will add the new wormhole

##### Scope "jumpbridge"

- will just track k-space to k-space jumps when there is no stargate between them.

**Comment by ZarosTenjin** [comment]
i really like this approach, gives everyone the behavior they want

**Comment by Calavoow** [comment]
What about a scope "all" and scope "none" (i.e. everything manual)? This filter could work very well. I would however name it something different other than `map scope`.

**Comment by Tupsi** [comment]
I partly agree with Calavoow, you should add the options "all" and "none" as well, just for completeness. "Map scope" though seems the perfect name for it, as its describing as it can get (you define the scope of the automated tracking by it). Although of course just add a line with a comment beneath it like "Choose what connections get tracked" wouldn't hurt either :-)

**Comment by exodus4d** [comment]
Note: The basic logic is already implemented. The implementation should also fix some tracking bugs (e.g. #185).

Is there a use case for map tracking based on `trueSec`? e.g. just track *HighSec* jumps, or *LowSec* jumps? Otherwise I will concentrate on `w-space` and `k-space` distinction only.

![map_scope](https://cloud.githubusercontent.com/assets/9299033/15984826/0412c8c6-2fd9-11e6-96f2-7a84b4d57f54.png)

**Comment by Calavoow** [comment]
If I see the interface, wouldn't checkboxes be more appropriate for the scope? E.g. track wormhole & jumpbridges, but not stargates. And if you check all, it tracks all jumps, if none it tracks no jumps.

I can't think of a usecase to distinguish between truesec. I talked it over with a couple of corpmates, and there did not seem a use case for it. Maybe something related to sec status, i.e. not being able to fly through highsec. But even that is solved by tracking all k-space jumps.

**Comment by exodus4d** [comment]
Oh, I just realized that a "jumpbridge" scope can´t be implemented :( There is no way to figure out if it is a `wormhole` or `jumpbridge` when someone jumped from k-space to k-space...

Stargate detection is of course working "fine", I do a "route search" between source/target systems. If this returns "1 jump", it is **very likely** a stargate. There is just a very small chance that there is direct k-space to k-space wormhole between neighbored systems.

So you have to manually switch the connection type for `jumpbridges`. When we drop `jumpbridges`from the select, we don´t need checkboxes because the "all/none" option already catches the rest.

The algorithm behind this "jump tracking" and auto-adding new holes is pretty complex. A lot more complex than i expected it to be. But the good point about this is, that we now have a "route history" for each pilot, so we could add a small panel with the last X-jumps (where he came from) somewhere, if this is useful in future.

**Comment by exodus4d** [comment]
##### Feature is ready for testing 
- https://www.dev.pathfinder-w.space (current `develop`branch is deployed)
- related commit: 2a73bb3018c762d90459a6ca4eeb9b3adc0666e0
- "**map scopes**" can be changed at any time, The map scope will **not** affect any systems already on the map! It is just responsible for new systems.
- the "**manual**" dialog was updated with the new map scope information

Technical information:
- The tracking logic was moved from the [client ](https://github.com/exodus4d/pathfinder/commit/2a73bb3018c762d90459a6ca4eeb9b3adc0666e0#diff-630f9aae23d2da6473a482c15e3f6246L3152)(*javascript*) to the [backend ](https://github.com/exodus4d/pathfinder/commit/2a73bb3018c762d90459a6ca4eeb9b3adc0666e0#diff-4782f2a4935a947f2d6516898f5d5ec0R758)(*PHP*)
- The update time (e.g. when new systems were added automatically) could be reduced by 40% (there is no additional *ajax* request required). So we went from ~ **5-10s** to ~ **3-7s**.
- This should fix some problems (like #185) as well

***

###### Example - New "stargates" (k-space) map scope:

Here is a small example for the new "stargates" map scope. I made some jumps on a clean map:

> "Hentogaira" -> "C2 (J122137)" -> "C4" -> "C3" -> "C1 (J151106)" -> "Lamadent" -> "Miroitem"

The w-space entrance systems were added (C2 and C1). w-space to w-space jumps (C2 -> C4, C4 ->C3 and C3 -> C1) were not added automatically. Stargate detection (Lamadent -> Miroitem) works fine as well :)

"**Wormholes**" map scope has a *reverse* logic. w-space jumps are tracked, k-space -> k-space jumps are tracked if it was no stargate (Unfortunately I could not test this, there was no k-space to k-space WH on SISI... ). Chain exit systems are added as well.

![k-space_chain](https://cloud.githubusercontent.com/assets/9299033/15990549/f0b8067a-3095-11e6-887b-b4120e3e3179.png)
