### ISSUE TITLE
Occasional 403 or 404 on F3 routes

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#142]
I get these randomly and I haven't been able to narrow them down, I'm hoping you've seen them before.

`PHP message: [app/lib/db/sql/session.php:76] Base->error(403)
PHP message: [app/lib/base.php:2672] session_start()
PHP message: [app/main/controller/controller.php:99] Preview->render('templates/view/index.html')`

This can happen when hitting @login for the first time or when you refresh on /map but my logs are littered with 403's and it happens to me on occasion.

Any ideas?

**Comment by exodus4d** [comment]
I never came up with this problem, but i have a suggestion:
First I would like to know since when this happened?- I pushed a framework upgrade of "Fat-Free-Framework" (`v.3.5.0` -> `v3.5.1`) to `develop` branch yesterday. So this upgrade could cause the problem. I had to do this upgrade because some bugs were fixed I contributed to:(https://github.com/bcosca/fatfree/issues/908)

##### My Assumption 
Your **IP** has changed.

##### The "Problem" in detail
In `v3.5.1` DB-Session handling was improved/fixed [sql\session.php L69 following...](https://github.com/bcosca/fatfree/commit/943df693fa3b183f7fec6fb09f9c9f89413228e6#diff-fa0f95c0b4fee5c71509107d1f61d8b0R69). A default `onsuspect();` callback handler was added to the Session `read();` function which should help to protect against [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) attacks. As you can see, the new default handler checks for **IP** or **User-Agent** changed and invalidates the current Session as "suspect" with a HTTP 403.
This problem was also discussed in here: https://github.com/bcosca/fatfree/issues/762

##### The Solution
Ill hand over my own `onsuspect()` callback handler to the `DB\SQL\SESSION();` constructor [controller.php#L118](https://github.com/exodus4d/pathfinder/blob/develop/app/main/controller/controller.php#L118).
Official doku: http://fatfreeframework.com/session#onsuspect .
So this is not really a bug, rather a security "feature" which is probably a bit to "strict". ;)

**Comment by exodus4d** [comment]
- IP changes are no longer validated as "suspect session".
  - If this becomes a security problem in future, We should revert this! I don´t know if this is a problem with the IGB or desktop browser. 
  - I don´t know why they added this validation, it doesn't  make sense to me. - Particularly in a *Single-Page-App* like *Pathfinder*. 

        > "[...] IPs can change at any time - the idea behind HTTP is that each request is independent. [...]"
"[...] you shouldn't track IP changes for 'security' - the only exception is if you can deal with geoIP features, and want to disable/annoy users of various anonymisation services. [...]"
      http://stackoverflow.com/a/7550915/4329969
- In order to obtain some data about IP-changed-sessions, these changes are logged in `log/session_suspect.log`
- *User-Agent* changes are still handled as "suspect" and trigger a 403, clear_session and remove session_cookie

**Comment by atkinsj** [comment]
Thanks Exodus,

That seems reasonable. I agree that IP address tracking is not a good way to identify user behaviours or to detect suspect behaviour. In my case I'm sitting behind CloudFlare (a CDN provider) so all my users appear as the upstream CDN providers IP (which rotates between a few ranges) to Pathfinder.

This likely explains my issue.

**Comment by exodus4d** [comment]
##### Off topic:
@atkinsj I have some personal questions about your experience with *CloudFare*. I have no background knowledge of CDN providers. 
- What is the primary reason you use it for? 
- What is your experience? - Would you recommend it?
- Can you provide any stats/info or a comparison running *Pathfinder* with/without a CDN? 

I´m currently setting up a new public testing environment (`dev.pathfinder-w.space`), running the latest `develop` commit. Maybe it is worth to give it a try on this domain? I´m on a *DigitalOcean‎* VPS 2GB RAM, 2 CORS

**Comment by atkinsj** [comment]
Hey mate,

I have always had good experiences with CDN's. CloudFlare is free on their basic level so worth a shot. You basically change your domains nameservers to CloudFlare's and then manage your DNS there -- once you set an A/AAAA record you can click a button to have it proxied through their service and they just update the records to their own.

Security benefits:
- Your servers IP is never exposed: only CloudFlare's
- They handle all the SSL and you don't need to worry about certificates (though you can do an SSL certificate between your server and CloudFlare and they even support authenticated SSL to ensure it's them)
- I firewall my server so that only the list of IP addresses CloudFlare use are allowed in via 443 and 80 is completely disabled. HTTP -> HTTPS redirection is then handled by them.
- They throttle web requests and suspected DDoS as well as vulnerability scanners etc

Performance benefits:
- Given that Pathfinder is heavy on the AJAX, you won't see a huge performance increase
- You will theoretically see a performance loss on AJAX calls since you're adding an extra hop however because they are a CDN, their servers are always close to the user no matter where the user is so the AJAX performance loss is negligible (I've not been able to measure it in my tests)
- Any static content is stored cached by the CDN close to the user: that means all your images, all your javascript, all your CSS is typically within <20ms of the user no matter where in the world they are

Side benefits:
- They fully support cache busting with query string, so no issues there (you can opt to purge the cache manually if you want)
- Their services are fully available over IPv6 even if your server isn't (mine is anyway but might help some)
- You get analytics on % usage, unique visitors, which countries they come from, what referrers they come in from, etc

I'm using it on my development domain while I get ready to transition to a new host and the stats for caching after about an hour of use are: 27.28 MB saved -- 73.42 MB total bandwidth. That's not too interesting since bandwidth is unlimited except that it is 27.28MB of content served within <20ms of the user.

Hope that helps.
