### ISSUE TITLE
Various IGB issues on the new development branch

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#144]
A couple of issues in the IGB on the new branch:
- A "Character not found" pops up in the bottom right corner constantly
- If you select System 1, then click System 2 then try to click System 1 again, you can't select it
- The routes and killboard modules do not show in the IGB

**Comment by exodus4d** [comment]
The "Character not found" warning, was just a relic from the API-Key authentication from previous versions of *Pathfinder*. The character who logged into *Pathfinder* always matched the current active in game character who uses the IGB. So, if a character was using the IGB but **no** log data (current system) were found, API keys were not added.
This has changed now. You can log in **any** character. Even characters that don´t match the one you are currently playing on the IGB. If this is the case, current location data is **not** updated from IGB Headers (because characters ids don´t match), instead data is pulled from CREST.

Summarized:
- **If** you are using the IGB **and** your `character->id == $headers['Eve-Charid']` -> Location (Log) data is used from IGB Headers.
  - No CREST Call required (faster)
  - Current Ship/ShipName/ShipId is available from `$headers` as well
- **else** Location (Log) data is pulled from CREST
  - Additional CREST call is required
  - Ship/ShipName/ShipId is not available by CREST at the moment.... :(

**Comment by exodus4d** [comment]
The "routes" table was not shown because of a JS error.... The JS engine used by the IGB (7 years old,....) doesn´t like object property names like `delete`. So I renamed them to `clear` ;)
