### ISSUE TITLE
Status: "Not Found"

### ISSUE THREAD

**Issue by hplanet** [exodus4d/pathfinder#149]
> Error - 404
> Status: "Not Found". Use your browsers Back button to navigate to the page you have previously come from.

I try run in fixed IP on http://1.1.1.1/pathfinder/, and show this error.
What has not been found?

Avoided https

**Comment by antt1995** [comment]
I get the same on http://www.[mysite.com]/pathfinder

**Comment by exodus4d** [comment]
Please provide some more details. Which branch, version, server?
I guess you have an Apache web server. Running *Pathfinder* on a sub-dir (like `/pathfinder`) requires some small tweaks on the `.htaccess`

1. Make sure `mod_rewrite` is active on your server
2. Make sure `AllowOverride All` is set on your server (otherwise `.htaccess` files are ignored)
3. Set/un-comment `RewriteBase /pathfinder/` in your `.htaccess` file

More information: http://stackoverflow.com/a/5070350/4329969

It´s not a bug, its just a bad configuration on your side ;)

**Important:** The `.htaccess` which is part of the repo is just an **example** config file, which should work for most setups!
