### ISSUE TITLE
How to share a map with the alliance?

### ISSUE THREAD

**Issue by VivianMeally** [exodus4d/pathfinder#154]
Hello
How can i share a map with the alliance?

I dont see any sharing options under sharing. Only Corp and Private

**Comment by exodus4d** [comment]
Alliance maps were not implemented in `develop` branch so far. I added them.
You probably need to re-login with your chars by CCPs SSO, in order to get the character connected with the alliance data.

I have just tested it. Works fine for me with the new implementation.
If your active character is currently in an alliance, you should be able to see the alliance option under "settings->sharing" now.

**Comment by VivianMeally** [comment]
Logget out, updated, cleared tmp/ logged in again. Created new map, but still dont see it

**Comment by VivianMeally** [comment]
Its works, if i manually fill alliance table and assign it to my char.
But it dont happen automaticly

**Comment by exodus4d** [comment]
Alliance data is now requested by the CCPs XMLv2 API. Unfortunately CREST does not provide any alliance data on the character endpoint.

You need to re-auth by using the SSO to get the ally data imported and connected with your character.

**Comment by Tupsi** [comment]
can confirm, this is working on my installed develop branch. You even see your alliance logo in the cookied character login, nice! :-) :+1:
