### ISSUE TITLE
Generating "Leads To" info for signatures

### ISSUE THREAD

**Issue by Varghus** [exodus4d/pathfinder#171]
Would it be possible to associate signatures with where they lead to? After jumping through a wormhole a dialog box would ask which wormhole signature was used to make the connection. It could be taken a step further and limit the signatures to the wormhole types that could make that connection. So far we're not doing a good job of adding the leads to info to the descriptions.

**Comment by UserOO7** [comment]
This would be wonderful.  Right now, the shared map tells people what connections are available, but sharing sig IDs is all word-of-mouth, there is not a clear standard for recording the destination or the ship size that can pass through the wormhole.

It would also be wonderful if the map and sig list synchronized, so that updating the map updated the sig list, or vice versa.  Right now, an expired wormhole must be manually deleted twice, from map and from list.

Map is really nice, very cool to view and customize.  Just hoping to reduce some of the opportunities for user error when the same information is entered separately in two places :-)

**Comment by exodus4d** [comment]
I close this as "duplicate". In #191 connection/signature labels are requested as new feature. This requires a new relation between "signatures" and "connections". This is also required for this Issue. If this is done, "delete on cascade" should work out of the box ;)
