### ISSUE TITLE
Add a way to force synchronise the map layout

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#185]
If multiple people are viewing the same map, they need to refresh to get updates to the map layout. This means that a map is often relaid out by multiple people who think it has not been touched.

Changes to the layout from one person should sync to the others. We could do this every 30 seconds or so (it does not need to be live obviously).

**Comment by Tupsi** [comment]
this is (partly) not true. Most of the time, map updates do occur. But I also noticed that on some occasions it does not and people get left behind with updates and even get errors in return if they try to modify an already deleted entry by some other person. It seems that the update triffer gets stuck/disconnected at some point in time due to unknown reasons.

**Comment by exodus4d** [comment]
I found some potential problems with map update, when I worked on #132.
This is ready for testing, and will be available in the next release, which should be done next week.
