### ISSUE TITLE
Tracking continues via CREST even when website is not opened

### ISSUE THREAD

**Issue by IvandaNothabeer** [exodus4d/pathfinder#202]
The default value of "Map Tracking" is "on" and map tracking will always turn on when a map is opened. This leads to character tracking continuing for all registered users when users may not be expecting it or when the map is only being opened to view data.
- Default value for Map Tracking should be "Off"
- Map Tracking should turn "Off" whenever CREST cannot get character location data ie User has logged-off, Downtime, etc

**Comment by Tupsi** [comment]
i disagree. We like it as it is, as we get info from the lazy (read cant be arsed to open a browser) people as well.

**Comment by IvandaNothabeer** [comment]
The quality of that information may be a little dubious ;)

Make it configurable anyway. IMHO my concern is that alliance wide maps already leak more data than I'm comfortable with anyway. I don't want every member of my alliance able to see the position of every other member using the map that my include FC's, scout alts, pvp gangs etc.

Really its all part of a wider need for a proper security system in pathfinder.

**Comment by Tupsi** [comment]
I can agree on the part that choice is always a good thing to have. And I did not put the alliance map option into a bigger picture, so you ar probably right. It is still eve we are talking about, I tend to forget that.

**Comment by exodus4d** [comment]
##### How it currently works:
When we talk about "Map tracking" there are two parts:
* Unmapped systems were automatically added to a map when a char enters a new system. This is configurable by the "map scope" of each map.
* Active char names are visible in each systems. This can not be turned off for now. But this does not effect auto-adding new systems to a map.

I added new "map scope" options in `v1.1.0`. This enables you to turn off map tracking for each map (#132). This just disables tracking for new systems but not character names in already existing systems. CREST tracking just tracks those characters who have a map open. Maps behind hidden tabs, are not tracked.
In case the browser tab is not active **or** the browser is minified,  CREST location tracking period changes from 5s to 20s (because of inactivity). This is reduces server-load.

A new option to turn off character names in systems is not a problem if you are fine with that?

**Comment by IvandaNothabeer** [comment]
Yes, turning off character names in systems is definitely a requirement, but this wasn't really my original issue.

There is definitely something strange happening with character tracking via CREST. Tracking does continue even after the users browser is closed and there is no map open. After looking at the code in more detail, I agree this isn't **supposed** to be happening....  but it is.

**Comment by garemoko** [comment]
One of the great benefits of this system is you don't have to have the browser open.  

The problem is that people have no way to control whether their location is shared and with who. I've got some ideas for adding permissions which I'll outline in a separate issue and probably open a pr for "soon"

**Comment by vivace-io** [comment]
I do believe there's a little toggle in the upper right that disables tracking for a character...?

**Comment by IvandaNothabeer** [comment]
> even when website is not opened

**Comment by benjhocking** [comment]
Possibly put this down as a advanced features request.

For my own corp we want everyone tracked. Because it means wormhole masses can be accurately tracked. Which saves time and makes hole rolling for lower sp players easier.

That said for larger alliances I understand that OPP sec is a huge issue.

Again a option screen could be the way to go.
#Benvolunteering

**Comment by exodus4d** [comment]
This isse is no longer relevant. _Pathfinder_ switched from *CREST* to *ESI* API witn v1.2.2
