### ISSUE TITLE
Delete all connected systems

### ISSUE THREAD

**Issue by garemoko** [exodus4d/pathfinder#211]
If a wh from your home space dies, you want to remove all systems inside that hole too.

I saw that you can multi select systems but there doesn't seem to be a way to delete all once you select them.

**Comment by exodus4d** [comment]
Sure, you can :) 

- Select multiple systems either by dragging a new selection **or** hold `CTRL` + `click` on systems.
- Then `right click` somewhere on the map and choose "delete systems" and delete multiple systems at once. When you `right click` on a system instead of empty map space you get the context menu of a single system.

Please reopen if you still have problems with this.

**Comment by garemoko** [comment]
@exodus4d thanks!
