### ISSUE TITLE
Can't import an exported map

### ISSUE THREAD

**Issue by Ligraph** [exodus4d/pathfinder#224]
So I'm trying to move my map over to a private alliance server, but when I export it from public and import it onto the private server, I get a 500: import map error.  I can supply the map if needed (privately).  This happens even when importing to the public server.

**Comment by exodus4d** [comment]
Please send me your map you want to import. I´ll  check it. pathfinder@exodus4d.de
I can´t reproduce this on the current `develop` branch :(

**Comment by exodus4d** [comment]
Thanks. This is not really a bug, more a misconfiguration on server side.
You need to increase `max_input_vars` in your `php.ini` / `.htaccess` or `httpd.conf` in order to import larger maps (> ~30 systems).

*PHP* default is `1000`. Change it to `3000` and it should work. This is not a "must have" but if you want to import larger maps you should change it.

##### I added a new requirement check to `/setup` URL:

![setup_requirements](https://cloud.githubusercontent.com/assets/9299033/16568894/0a2d98d0-4230-11e6-8df1-58cd35d26b21.png)

I´ll change it on my servers soon.
