### ISSUE TITLE
[Feature] Intel fields (Pos/Citadel)

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#246]
Please consider adding a POS/Citadel tracking details with in Systems

**Comment by exodus4d** [comment]
@dnolen please comment https://github.com/exodus4d/pathfinder/issues/184#issuecomment-241855447 what you think about this feature. I´ll probably implement both issues in the near future.

**Comment by dnolen** [comment]
Ideally what I think would be good to see implemented is some way of tracking planet/moon for Pos'  along with some area to enter in some dscan info about the config and owner information (perhaps link the corp info from a crest information lookup which can then be linked to evewho,zkill, etc) 

As for the Citadel the option of entering some form of relevant information like the above would be helpful

**Comment by dkrotil** [comment]
This is our current Intel , which we want to retain 
![image](https://cloud.githubusercontent.com/assets/10422726/17917602/2cece8d4-69be-11e6-9ccb-462652e05d87.png)

System should retain name and color , should have some tag "show only , when connected to other system" . 

For POS, Citadel info there need to be universal input form .  Name , type , online / offline. Some danger tag ( heavily bubbled with cans etc ) . Position is something tricky, is has some meaning for POS, but Citadel can be placed anywhere. 

For other info: 
- config I don´t think this should be added, to much info , which can very quickly change 
- owner is very important info, link to zkillboard is a plus

And very important aspect, there should be possibility to change info, ( edit, delete )

**Comment by exodus4d** [comment]
Thanks for your input!

The first step will probably be to change the way how systems behave on delete. 
The current behaviour is, that all system information (name, alias, description, signatures,...) will be deleted when a system was removed from a map.

I´ll use some kind of "active" state for systems. Deleted systems will become "inactive" (invisible). If someone adds them again on a map. All information should be still there.

The second step will be some kind of Citadel-tracking-UI for each system, where users can add more detailes information about that. 

I´ll probably not add any POS specific features (Moon position,..), because they will be deleted from the game soon.

**Comment by dkrotil** [comment]
For inactive state , I have one idea. When you rage roll it´s possibility to have static again very early. Can you make 2 stages inactive mode, first stage will be for 24 hours and will include probed signatures and second stage will drop signatures and left only basic info about system.

**Comment by exodus4d** [comment]
@dkrotil Thanks! The part about persistent system information will be done in #184. This needs to be done before the *POS/Citadel* feature can be implemented.

**Comment by exodus4d** [comment]
#### New Feature "_Intel module_" for _Citadel_ tracking

This can also be used for "_Engineering Complex_" and "_Refinery_" data.
There is new module implemented that allows tracking for Citadels per system.
- Stored Citadels are **persistent**. Deleting a system from map or even the map itself wil **not** delete tracked Citadels, The next time you map that system to a map, or even to another map, Citadels are still there.
- Citadel data always belongs to the **corporation**, the character who mapped that Citadel belongs to.
  - On "_private_" maps you see all Citadels, your corporation has stored over time.
  - On "_alliance_" maps you see all Citadels, from all corporations with map access
- Citadel data is **grouped** by the Corporation, that "owns" the citadel

E.G. You have map **corporation** map, shared between 2 corporations, you see all Citadels from both corporations with map access. You can view but not edit citadel data that does not belong to your corporation.

![ajuwsdu](https://user-images.githubusercontent.com/9299033/39493300-aae215c0-4d92-11e8-819a-5612915b35a9.png)

![sdeamtq](https://user-images.githubusercontent.com/9299033/39493303-af2f057a-4d92-11e8-8970-96140c362139.png)

**Comment by exodus4d** [comment]
D-Scan results can be pasted into your _Pathfinder_ Browser tab relevant Structure(Citadel) data will get parsed and auto updated the current selected system (Just press `ctrl` + `v`). 
This method is called *lazy update* because no form/dialog needs to be open where to paste the scanning result at.
It works the same way as *lazy update* for Signatures works.

![lazy_update_d-scan_and_signatures](https://user-images.githubusercontent.com/9299033/39662268-4c104b3c-505f-11e8-8e06-7854648e1e59.gif)
