### ISSUE TITLE
[Feature] Global addition of static route info

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#247]
Currently corp mates are asking to add Hek as a static trade hub. 

Can we please be given the option to add a persistant set of changes to the routes section and add Hek as a static there

**Comment by exodus4d** [comment]
Good feature! I´m thinking about a way to make it configurable per map. 
- Add a new *multiselect* for systems to "map settings" dialog.

**Comment by dnolen** [comment]
Additional Add Thera routes (Additional panel? Configurable by user/admin) this can map out kspace exits and jumps to them as they change

**Comment by exodus4d** [comment]
#### This will _probably_ be finished with the next release...

Changes to the "route finder" module:

- [ ] Remove current default systems from routes UI (*Amarr*, *Jita*, *Rens*, *Dodixi*)
- [ ] Add new "settings" icon to routes module, which opens a new settings dialog
 - [ ] Add *multiselect* systems search field  to it
 - [ ] Limit selection to **4** systems (make it configurable in `pathfinder.ini` ?)
 - [ ] Store selected systems to *LocalStorage (IndexedDB)* (individual configuration for each map)
- [ ] Add stored systems to route module table UI
- [ ] *Fallback:* If no systems were selected (e.g. new map), set *Jita* as default

#### WIP dialog:

![routes dialog](https://cloud.githubusercontent.com/assets/9299033/18255823/c2a4261e-73ad-11e6-87a1-2243e3c0d0d0.png)

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
