### ISSUE TITLE
[BUG] - Offline pilot status not updating

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#249]
Issue: Map is still showing pilots as online in systems once client has been closed - Crest API location details are not syncing. 

Example: I have added trade hubs to our default map. In this case the pilot logged off in Amarr (or this is shown as the current last known location)

**Comment by WildStrawberryEVE** [comment]
I encountered the same problem. I locked one wormhole system (home) and few pilots are listed as permanently online in that system.
Is there any way to "flush" the system's list of pilots and possibly force pathfinder to get new data?

**Comment by exodus4d** [comment]
Have you checked your Cronjob to be working?
Offline/Inactive pilotes should be auto-deleted after 10min.

The "problem" is a way more complex here:
- The current location is pulled from CREST every few seconds. This requires the character to be **online**.
- The *CREST* limitations we have to deal/work with:
 - I **can´t** pull location updates for multiple characters at once (there is no bulk endpoint available)
 - I **can´t** pull location updates by **Cronjob** because of the *CREST* request limit of 150/s
 - *CREST* is not a **push** API. *PF* has to request *CREST* for updates (I can´t get auto-informed about "offline" pilots by *CREST*)

So the only way to delete inactive/offline chars is a Cronjob. This is the way to go.
