### ISSUE TITLE
[Change Request] Update Status stages in right click menu

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#251]
Not sure if this is a valid request and how other corps call stages for holes but can we please have the mass Indicators changed to Stage 1 (Normal), Stage 2( Half Mass), Stage 3 (EOL) in the right click menu? 

Most of the time we call the hole as Stage 2 when switching states in other mappers.

**Comment by garemoko** [comment]
There are already separate settings for mass

**Comment by dnolen** [comment]
Yes, but they are counting 0, 1, 2. 
pretty sure most groups call holes by stage 1 (fresh), Stage 2 (reduced), Stage 3 (VOC)

Updated original subject

**Comment by exodus4d** [comment]
Renaming the options is not a big deal :) But I have never heard about "stage 3" to be EOL. 

Ill ask some WH groups about that, If the majority prefer a renaming - I´ll do ;)

**Comment by dnolen** [comment]
@exodus4d  Most groups I've flown with refer to half mass as  stage two.  EOL just is called as such but it was just a point of confusion someone mentioned when working with the mapper.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
