### ISSUE TITLE
[Change Request] Security on Routes panel should exclude starting system

### ISSUE THREAD

**Issue by Grookshank** [exodus4d/pathfinder#258]
The average security on the Routes panel should exclude the starting system, since it is not relevant to see how secure/unsecure a route is (assuming you will start from that system).

**Comment by dnolen** [comment]
Can we also have the option to set the route via secure/shortest/less secure?

**Comment by exodus4d** [comment]
@Grookshank: Good change request! Ill add this.

@dnolen: The route calculation algorithm is very CPU intensive. Even now it takes some seconds of calculation for longer routes. And my *VPS* is not weak :)
Adding more parameters to that algorithm, without heavy caching, could kill it ;) So this would be nice to have in future but not any time soon :(

**Comment by dnolen** [comment]
@exodus4d I'm not sure how you are currently calculating the route based around the logic in the code, however it appears it maybe the shortest path. 
My corpmates had questions based around the route vs. autopiloting path when we were looking it in Kspace

**Comment by exodus4d** [comment]
Yes it should be the shortest path for now.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
