### ISSUE TITLE
[BUG] Shatter wormhole sites are not populating 

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#260]
Issue: 
Errors are being reported when attempting to add sites to the signature adder 

ONS-344    Cosmic Signature    Data Site    Unsecured Core Emergence     100.0%    9.63 AU
ULC-318    Cosmic Signature    Data Site    Unsecured Core Backup Array    100.0%    44.28 AU

No errors are populated however sigs are not added. 

Jcode of sig J001820 - C5 Shattered

**Comment by exodus4d** [comment]
**This works for me. But there is one important fact:**

You can **not** simply copy&paste signature data between multiple apps/chat/ what ever! Signature strings were parsed and split up by "**tab stop**"! 
When you copy a signature string from the client somewhere else, it is *most very likely* converted into _spaces_ .

To make it more clear. Look at this example. It shows your signature string in [Notepad++](https://notepad-plus-plus.org/).  With **active** "show all characters" option.
Then replace the column delimiter with **tab-stop** (orange arrow).
The first example fails, the second one succeeded:

![test](https://cloud.githubusercontent.com/assets/9299033/17096862/adf53d8e-525b-11e6-8adf-1ca7e388cf18.png)


Can you confirm this?

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
