### ISSUE TITLE
[UPDATE] Inbound wormhole K162 - Thera missing from signature type list

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#261]
Please add "K162 - Thera" to the list of available K162 connections for outbound thera entries.

**Comment by Grookshank** [comment]
You mean a WH from Thera to Thera?

**Comment by dnolen** [comment]
No, the flavour text on outbound static from thera reads "Connected to Thera" or something like that. 
In the list of options in the signature adder under Type there is no K162 - Thera under the incoming wormholes options 

http://i.imgur.com/uR0KLZ8.png

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
