### ISSUE TITLE
killboard entries show wrong date (month-1)

### ISSUE THREAD

**Issue by Tupsi** [exodus4d/pathfinder#268]
the fetched kills from zkillboard are shown correctly, but with date one month in the past. So for instance I am currently looking at kills from 17h ago (which is correct when you click on a kill), but in the list they are all put into june instead of july.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
