### ISSUE TITLE
MySQL Versions prior to Version 5.6.5 are not supported

### ISSUE THREAD

**Issue by IvandaNothabeer** [exodus4d/pathfinder#27]
The database contains multiple tables that have two TIMESTAMP fields. This is not supported in versions of MySQL prior to version 5.6.5  Specifically, It is not possible to have the current timestamp be the default value for one column and the auto-update value for another column.

Several internet Hosting providers do not yet use this version of My SQL. For example Hostgator is still running at version 5.5.23 and cannot give any indication of a date when their MySQL version will be upgraded.

The problem with 2 columns and multiple timestamps is described here ...

http://stackoverflow.com/questions/267658/having-both-a-created-and-last-updated-timestamp-columns-in-mysql-4-0

**Comment by exodus4d** [comment]
Thanks for reporting! For now there are no plans to refactor the SQL Scheme and make it backwards compatible. The problem is, that refactoring *each individual* Model would take a long time. In most cases both timestamps are required to check for changes and/or update cache storage. 

I´ll check/update the Requirements section
