### ISSUE TITLE
[BUG] C2s missing pseudostatic wormhole type options

### ISSUE THREAD

**Issue by Adarnof** [exodus4d/pathfinder#276]
There is no option for pseudostatics when editing wormholes in class 2 systems.

To remedy, all the w-space C2 statics could be added to the Wandering Wormholes section of the type list:
 - Z647
 - D382
 - O477
 - Y683
 - N062
 - R474

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
