### ISSUE TITLE
Player tracking not working on Corporation Map

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#28]
Hello,

The player tracking ![](http://sakarias.eu/u/20150923195016.png) is not working as intended if I set my map to "CORPORATION", but that feature is working on "PRIVATE" and "ALLIANCE" maps.

**Comment by exodus4d** [comment]
Ill check. Player tracking is enabled in any map mode (Private, Corp, Ally). The way it should work is, that you see the current number of active pilots in a system. 

Green means: Player number "increase"
Red means: Player number "decrease"

The screenshot looks good for me. Even if there are more than 1 player active in a system, there is just one player name visible. If you want to see more information and all other players, hover the small gray arrow next to the system name, the system should enlarge and all Players and all their ships should be shown.

Moreover, a green "dot" before a Player Name means, that he is in your Corp, blue = same Ally. 

What exactly is your problem here?

**Comment by Sakarias-Longhorn** [comment]
Yes,  it's a screenshot of how it is supposed to work (so you know what I'm talking about), the bug is that on a corporation shared map, nothing happens, you can't see other pilots at all, while its working with the alliance and private maps

**Comment by exodus4d** [comment]
Ah okay i see. Thanks, Ill look at this.

**Comment by exodus4d** [comment]
This is fixed in v.0.0.11
