### ISSUE TITLE
[Bug] Where I´m 

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#281]
In Siggy , which was our former WH mapping tool was very easy to know , where is current character located. Can you add this , maybe as settable feature, to highlight current position of character on the map ?

Thanks

**Comment by exodus4d** [comment]
There is already a feature implemented. You should see the system name in the top navigation bar where you in (and systems is mapped). When you click on that, the system should be selected on the map.

**Comment by dkrotil** [comment]
Yes I see current location on navigation bar but , when I click on it, it does nothing. Tried in FF and Chrome.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
