### ISSUE TITLE
[Feature Request] Magnetizing doesn´t survive browser close

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#289]
Hi,
can you add saving of Magnetizing feature ?

Thanks

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
