### ISSUE TITLE
Ability to specify the signature ID of a connection

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#290]
A new context menu option on connections to specify which signature ID type it is would be amazing. I have a cronjob set-up to EOL old connections at 48 hours but if I could EOL them based on their signature ID that would be even better.

I know we've talked about this at various times but I wanted to track it in an issue on it's own as I think this is the best approach.
- Right click -> set signature ID
- Get dropdown of completely unfiltered (i.e., every possible signature id in the game, don't bother about filtering based on the source system type as this is just creating issues IMO)

**Comment by dkrotil** [comment]
Someone asked to set timer for EOL connections, I´m not sure if this request isn´t contrary to it.

**Comment by atkinsj** [comment]
Setting the connection to the correct signature ID brings a lot of benefits; being able to filter routes based on ship size, mass, etc comes to mind primarily. I feel like the request to manually specify an EOL timer is just a hack to get around the fact that we can't age them out appropriately because they're not linked to the signature.

**Comment by dkrotil** [comment]
I think connection ID can be set automatically from information , which systems is interconnecting. Only frig size and couple exceptions are there ... .

**Comment by exodus4d** [comment]
@atkinsj Adding a new option to the contextmenu of a connection would be difficult:

1. There are always **two** signature IDs in two systems that are connected. Wouldn't it be better to add a new select to the signature table to select the connection?
2. How to other mapping tools (Tripwire, Siggy,...) handle this problem?

**Comment by Grookshank** [comment]
1. It is basically the same as in https://github.com/exodus4d/pathfinder/pull/228. The goal is being able to add and delete entries in siglist and map in one go.
2. If you add a signature to the list in Siggy, you can select a target system you already have on the map. It then autolinks those two, so when you delete one, it deletes the other.

**Comment by atkinsj** [comment]
@exodus4d sorry, I missed this reply.

> There are always two signature IDs in two systems that are connected. Wouldn't it be better to add a new select to the signature table to select the connection?

Only one of these is 'true'. The K162 is irrelevant: I wouldn't even make it available as a context menu options. If you aren't jumping through the hole to get the true signature ID then you aren't in need of this feature (but you really should be, to both).

This makes the data that's already in the signature reader applicable to users in a much more useful way but it doesn't replace the signature reader, you need both. There are some signatures that last 16 hours, there some that last 48. If you can mark a connection with the signature ID then we can have a cronjob that could automatically mark holes as EOL based on the signature ID.

The information is there to do that right now but it's not linked to the connection, so we can't do anything with it.

**Comment by Bingmano** [comment]
This has been requested already #191

**Comment by Bluedagger21** [comment]
First time posting on this project. I've been doing some research into Pathfinder as an alternative or backup from Tripwire. I really like the functionality and interface, but it is this issue that is causing me to not use this tool. Without it, we are (at least) doubling the workload of managing our map connections.

Tripwire does the following with Auto-Mapper turned on: 

A new K162 wormhole is found. Its signature id is known (through copy and pasting probe scan results). This immediately adds a blank "new" system  attached to the sig id in the map with simply a labeling of K162 since no additional information is known. The user can still modify EOL and mass levels. This also has a "Leads:" field which the user can enter any system name OR the class of wormhole (which can be visually and/or textually identified without going through). The user can even put in High-Sec if the description of the wormhole says so.
![tripwire-modify](https://cloud.githubusercontent.com/assets/2181149/19612814/98b114d4-979d-11e6-8cad-8cc456c01bbd.PNG)

This will then be reflected upon the signature list:
![tripwire-siglist](https://cloud.githubusercontent.com/assets/2181149/19612818/9d86ee0c-979d-11e6-9130-cf8897af7225.PNG)

And the system map:
![tripwire-systems](https://cloud.githubusercontent.com/assets/2181149/19612821/a247d03c-979d-11e6-9173-93823eadc0d1.PNG)

If the user then enters a K162, Tripwire will verify the destination system cannot match any other connection and verify it is unique. If it is unique, it will automatically update the "Leads:" field with the actual system name, create a new signature in the destination system with "Leads:" set to the source system with unknown sig id, and then switch context to the new system if following is enabled. If there is a conflict to find a unique system for the destination, a prompt will appear asking which of the conflicting signatures the user jumped through. This establishes the correct connection.

Deleting any of the wormhole or gate type signatures will break that chain. I realize that pathfinder is setup to be a bit more persistent, keeping a chain around even if it has no connections. That is fine, it is easy to select the now disconnected group and delete them in the system view. 

Ok, that was a lot to type, hopefully I didn't go off tangent too much from this thread. In any case, this issue currently forces us to make many many more clicks and typing than Tripwire does.

**Comment by exodus4d** [comment]
#### 
![fax9yyh](https://cloud.githubusercontent.com/assets/9299033/22668342/b11a33fc-ecc0-11e6-8208-30c15cea69c0.png)
WIP

**Comment by exodus4d** [comment]
There are a lot feature requests in this issue. I haven´t implemented them all but I did some groundwork for further features.

#### Changes:
- **Signatures** can be connected to **connections**(e.g. wormholes).
  - New "leads to" column with select options with all connections in the current system
  - This column is just editable for signature type "wormhole"
- Multiple signatures can be connected with a single connections (which does not make much sense). Therefore I implemented a **conflict check** that validates all connected signatures.
  - If there are more than **1** signature connected with a connected, a red warning icon is visible next to the signatures that have a conflict.
  - This check is also available for new signatures that have not been saved yet (see image below)

![a3pq6yf](https://cloud.githubusercontent.com/assets/9299033/22855154/7970d0b4-f07b-11e6-80f4-96bc6ae0263d.png)

**Comment by exodus4d** [comment]
Check https://github.com/exodus4d/pathfinder/issues/334#issuecomment-279226205 for upcoming UI changes (new overlays)....
