### ISSUE TITLE
Typo in pathfinder.ini 

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#292]
[PATHFINDER.ROUTE]
; max recursive search depth for routes (default: 70000)
; decrease it on performance problems
SEARCH_DEPTH                =   7000

Default in description is 70 000, but value is 7 000 .

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
