### ISSUE TITLE
Broken (player count) tooltip after system movement

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#30]
Hello,

So sometimes, this happens : 
![](http://sakarias.eu/u/20150925202659.png)

Also when I set the 

>; time for status change visibility in header (ms)
>PROGRAM_STATUS_VISIBLE = 1000

>[PATHFINDER.TIMER.UPDATE_SERVER_USER_DATA]
>DELAY = 1000

(To make it faster to refresh data) it's just glitching a bit.. for exemple if someone jumps from a WH to another, it creates the new wormhole label, but it doesn't add any link to it.

**Comment by exodus4d** [comment]
Do you have v0.0.10 installed? this should already be fixed

**Comment by Sakarias-Longhorn** [comment]
Yes,  0.0.10

**Comment by exodus4d** [comment]
Thanks for testing! If you like it, feel free to write a short review in the official forum thread ;)

**Comment by exodus4d** [comment]
OK, I´m able reproduce this. This happens when jumping between systems (`playerCount` tooltip updates). Up to this point everything is fine.By moving the previous system around on the map, the tooltips break up and shows HTML.

**Comment by exodus4d** [comment]
@Sakarias-Longhorn: For now, I would advise against changing the the timers e.g.

> [PATHFINDER.TIMER.UPDATE_SERVER_USER_DATA]

During development, i experimented a lot with the timing trigger interval. If you change the timings you, have to change some other values too. The default caching time fore some models is hardcoded e.g.
https://github.com/exodus4d/pathfinder/blob/master/app/main/controller/controller.php L.79 Die default object cache time for the current `UserModel` Object is seit to 5 = 5000ms. I´ll probably move all this configuration stuff into the `pathfinder.ini` soon.

Further more, `Pathfinder already has some functionality, to adopt the timings **dynamically** to the current user behaviour :) If you use the Program with your OGB and you switch the focus to another Tab, die interval is reduced because I expect, the user is more or less "AFK" and not interested in a second precise update cycle.

https://github.com/exodus4d/pathfinder/blob/master/js/app/page.js L.859

You can check this by opening your browser console, or the *Task Mangager Dialog* in Pathfinder, You should see the default timings above each graph, now switch to an other Tab, wait  5sec and switch back. The Timings changed from 5000ms to 15000ms. When the next update interval starts and your tab is active agian, the timings will also switch back to 5000ms. This has a massive improvements in server performance. And "inactive" players don´t become their maps updated as quick as others.
