### ISSUE TITLE
database pathfinder installation error

### ISSUE THREAD

**Issue by fackir** [exodus4d/pathfinder#300]
SQL-запрос:

--
-- Database: `pathfinder`
--
--
-- Truncate table before insert `wormhole`
--
TRUNCATE TABLE  `wormhole` ;

#1146 - Table 'pathfinder.wormhole' doesn't exist

**Comment by exodus4d** [comment]
### :grey_question: Bug details required
Thanks for your bug report. Unfortunately I couldn't verify/reproduce this. :disappointed:
Could you please provide us with some detailed information about this issue...

- **Version:** Which version of *Pathfinder* is being used? (e.g. `v1.1.2`)
- **Server:** Which server/installation is being used? (e.g. "*private*" or "*public*")
- **Browser:** On which browser have you determined this issue? (e.g. "*Chrome v52*")
- **Frequency:** How often have you seen this bug? (e.g. "This happens **any time** a user clicks on a System.")
- **Reproducible:** If you found a way to reproduce this, please tell us how.

#### If this bug is on a "*private*" server/installation, please add additional environment information that could be helpful:

- **Web-Server:** (e.g. "*Nginx*", "*Apache*")
- **PHP:** (e.g. `v7.0.8`)
- **Database:** (e.g "*MySql v5.6*")

***
*Auto-generated response*

**Comment by fackir** [comment]
**pathfinder-1.1.3
Web-Server: Apache
PHP 5.6
Database mariadb 5 ,mariadb10, mysql
ubuntu 14.04**
I am doing import Databases; through phpmyadmin through the installer / setup
also embed SQL Dump
one and the same error is set to an empty server apache php5.6 installed MariaDB database and MySql is always one and the same error
Database: pathfinder

- Truncate table before insert wormhole

TRUNCATE TABLE wormhole;
dobovlenii wormhole at the table manually before it passes sleduyschey table and throws an error
and eve_citadel_min.sql table is imported properly
you can throw a table dump

**Comment by dkrotil** [comment]
@fackir is this update ? If not then pathfinder DB should be empty, no tables there.

**Comment by fackir** [comment]
the database is empty put on an empty server

**Comment by dkrotil** [comment]
On setup page is everything in green ?

**Comment by fackir** [comment]
yes all the basic settings in the green today porprobval once again all set to install with no problems ..... he did not understand what the Problem Thank you for your assistance will help the development of our corporation)))
