### ISSUE TITLE
[Feature Request] Possibility to change route calculation

### ISSUE THREAD

**Issue by dkrotil** [exodus4d/pathfinder#311]
Currently there are Routes calculated as shortest path. We would love to have possibility to change on the fly to Prefer safer, mostly because , when character is in High Sec and looks on Routes he want to see how to get to the trade hub though 0,5+ systems.

**Comment by exodus4d** [comment]
This  feature will be part of the next release `1.2.0`. I added a new icon (shield) which can be clicked to toggle a "save" route. The icon turns into green if active:

![route](https://cloud.githubusercontent.com/assets/9299033/21582289/93ffd582-d051-11e6-8be5-c2e7a44f76ff.png)

#### How it works:

- Any system lower than ** 0.45** (> 0.45 is rouned to 0.5 = HighSec) will be removed from the systems that will be searched in.
- The direct **source** and **target** systems will **not** be removed. 
  - E.g. If you are in a system/wh with a direct HS neighbor, you are able to find a save route as well. In case your target system is a HS system (and not a HS island)
- "Safe routes" are not the new default for searches. Otherwise wormhole groups could not find any HS exit deeper in the chain.
