### ISSUE TITLE
[WIP] New "collision detection" for systems (Magnetization )

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [exodus4d/pathfinder#32]
Hello again,

When (for exemple), you start from a WH and you go visit 3 other WH's from the same wormhole, that happens

![](http://sakarias.eu/u/20150925203326.png)

They all stack up and you have to move them manually.

**Comment by exodus4d** [comment]
Yeah i know. It is not really a bug. It works as expected :) Each new system has an offset of ( "`currentSystemXCoordinate + 130px`", that will add any new system to the right of your current system.

The only valid solution, is a kind of "collision detection", that will check for overlapping. This can be realy hard to implement especially if there are a lot systems on a map. There is a very nice extension for the jQuery plugin Im using:

http://morrisonpitt.com/farahey/#demo8 (last example)

But that can be confusing or lead to unexpected or not intended behaviour. So for now this is fine.

**Comment by exodus4d** [comment]
I made a short [video](https://www.youtube.com/watch?v=uSNDAIUo51c&hd=1) with the current WIP state.

**Comment by exodus4d** [comment]
There will be a new *BETA* feature in the upcoming  `v.0.0.14`. It is called **Magnetization** (bad wording I know ;) any other suggestions?).
- If active, systems effect each other while `drag&drop` or  moving around on a map. (check the video above, to get an idea what i mean)
- If active, new systems added to the map, will automatically rearrange others that are in its way and prevent "overlapping" of systems.
- The *collision detection* even works while moving **multiple** systems at once around on a map.

Because of the complexity of this feature, it will be shipped out as *BETA* and will be continuously improved over the next releas iterations. (minor priority)

There are some known minor bugs:
- The combination of **Grid napping** and **Magnetization** does not work as intendet.
- Auto updated systems on a map, are not automatically rearranged as intendet.
- A context menu option is not implemented yet (e.g. `right click` system ->  `rearrange`)

![pathfinder_magnet_feature](https://cloud.githubusercontent.com/assets/9299033/10715963/8581b27a-7b28-11e5-86aa-6c53e8357177.png)
