### ISSUE TITLE
Issues and New Features request

### ISSUE THREAD

**Issue by Bellerian** [exodus4d/pathfinder#320]
I put down several notes when testing this mapper out and I have a few issues with it, mostly minor with exception to issue number 1.

Issue 1: Using mapper for multiple accounts
Precondition: Two tabbed Maps: Mapper A, Mapper B, Two Accounts are logged in, Account A and Account B.  Both Accounts are actively mapping.

1a. If I'm using Account B on Mapper B, then switch back to Mapper A. Mapper B System that user is in is now added to Mapper A.

1b. If I'm using Account B, but jump through a hole using Account A.  Account A jump is not register on Mapper A.  Also it appears only one account can be active at one time which could be the issue.

So if I have multiple toons flying through the chain, only one account is viewable.
There's no work around for this, can't launch multiple broswers for each account as it will throw a security error and log out both browsers.

Issue 2: Lag/Update with new Sigs
Sig updates are slow when using signature reader, they don't automatically refresh, user has to click on the system for the sigs to display.  Same thing goes for sigs that are to be deleted don't remove until the system is clicked again.

Issue 3: Map Shaking switching tabs
Having map shake when switching between tabbed maps is annoying.  Not a good user experiance.

Issue 4: Moving Locked Systems
Some home systems (Locked) can't easily be moved. User has to continue to cover over until the grab option appears, or unlocked the system then move it.   This feature needs to improve.  As a user I don't not want to unlock move then lock, it's too many clicks.

New Features Request:
1. Ability to minimize the main mapper view and have the bottom view occupy the space.  That way a user doesn't have to scroll down to view additional intel.
2. Ability to have multiple characters logged and tracked at the same time without impacting the current view.
3. Changing all font to white will help it be easily read.  Currently reading the intel is a little hard on the eyes.
4. Ability to manually enter in sigs using keyboard functions and using tab to update sigs.

**Comment by dkrotil** [comment]
For issue 1 is duplicate see https://github.com/exodus4d/pathfinder/issues/314 
For issue 2  and 3  nobody complained about this , you are the first one, exodus4d will tell more, but I think this is how the framework works
For issue 4 , you can´t move it because is locked,complaining about that doesn´t make sense

Putting everything in one issue isn´t right and it will not help much. From developer view it can´t be handled properly.

**Comment by Bellerian** [comment]
For issue 4 the mapper does allow me to move the locked system on one tab not the other, it's not a complaint it's a bug.

**Comment by Bellerian** [comment]
Going forward I'll split out the issues.

**Comment by dkrotil** [comment]
@Bellerian not sure what you mean, I moved 15 wormhole system today from one side of the map to another and no issue. If the system is locked, then you need unlock it and after that you can move it.

**Comment by rmcginnis** [comment]
For Issue 3 I see this alot but it doesnt bother me or my corp mates.

**Comment by atkinsj** [comment]
Issue 3 was something I raised a while back. I've patched it out locally
since it was infuriating my alliance folk.

**Comment by rmcginnis** [comment]
How did you fix it?

**Comment by Bellerian** [comment]
@dkrotil the locked functionality should only prevent the home system to be accidentally deleted and it should retain the ability to freely move it around.

**Comment by atkinsj** [comment]
I'd wait until Exodus responds; he may be nice enough to add a toggle to
his todo list ;).

I patched the JavaScript manually in our fork so I'd have to go find the
diff.

**Comment by rmcginnis** [comment]
ok just curious i'll wait for it to be fixed in master if it ever does.

**Comment by dkrotil** [comment]
I see shaking only when switching map from right to left, switching back shows another animation

**Comment by dkrotil** [comment]
@Bellerian you are wrong, look on manual. Locked system can´t be selected, moved or deleted.

**Comment by Bellerian** [comment]
@dkrotil I might be wrong, but doesn't mean it should work that way.  Like the map shaking switching between tabs for example.

**Comment by exodus4d** [comment]
@Bellerian Thanks for your feedback. 
Please split this issue up. I´ll only work on Issues that can be closed/fixed in a closed/resolved at once. Those Issues with a collection of requests can not be prioritized and finally non of the requests will get done. 

I´ll close this Issue. Y**ou are welcome** to create new Issues with **one** topic each. This allows other to re-comment and discuss them.

Some notes:
1. Is duplicate: #314 (It will probably be resolved with the upcoming release)
2. This should already be fixed in the upcoming release (resolved in #310)
3. This just affects smaller maps **< 20 systems**: [map.js#L862](https://github.com/exodus4d/pathfinder/blob/master/js/app/map/map.js#L862)
4. This is exact the behavior of *locked* systems.... they can´t be moved/deleted. If you don´t want that -> don´t lock them...
