### ISSUE TITLE
[Feature] Login/home page usability

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#323]
It would be great if we could move the character selection up a bit higher/shrink that top feature bar so that characters are visible without scrolling down the page on landing. 

It would also be great if we could find a workaround for the delay before character selection on the home page as it really hinders usability on first landing.

**Comment by exodus4d** [comment]
Moving the character selection panels more into the view port is something I have in my mind for a long time. This is probably coming in future.

The delayed loading of the character panels is required. The cookie data is checked, validated and synchronized with current CREST data (which requires an Ajax call). So users are not able to login if CREST is down, character data gets invalid, character was sold,....
Switching between characters (or have more than one active character, coming with the next release) should be done over the character switch menu on the map view.

**Comment by exodus4d** [comment]
I reduced the height of the header ~120px. This is part of the `v 1.2.3` release

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
