### ISSUE TITLE
[Bug] 1.1.5 does not work with FF with private browsing enabled

### ISSUE THREAD

**Issue by Grookshank** [exodus4d/pathfinder#337]
The latest version of pathfinder just shows an empty screen with FF 49.0.1 (latest) with private browsing enabled. See http://imgur.com/a/qo9pK

It was not problem in previous versions.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
