### ISSUE TITLE
Feature Request: Automatic Alias for WHs

### ISSUE THREAD

**Issue by Kimeni** [exodus4d/pathfinder#360]
A non critical, but nice quality of life feature which my Corp misses, is having our mapper automatically give short easily identifiable names to our map as we populate wormholes.

For example, when in combat, or needing to quickly reference something down the chain, It's easier to Identify something as WH17 off of the B chain, rather than a J-sig.

If the launcher was able to give you the option to automatically name WHs with a WH##, sequentially, unless a lower number is no longer on the map, it would cut down on human error.

Potentially, Pathfinder could assign that number to a WH after you paste the sig, and select the type of wormhole, but adding Pathfinder's WH## to the Description field, also giving us a name for bookmarks on the spot as well.

**Comment by dnolen** [comment]
Linking my request as a duplicate >> https://github.com/exodus4d/pathfinder/issues/369

**Comment by exodus4d** [comment]
Thanks for your request 😄 . As I mentioned in https://github.com/exodus4d/pathfinder/issues/361#issuecomment-256410829, automatic "renaming" of new systems will not be implemented due to the large variety of different naming conventions out there.

But what we could talk about, is some kind of pre/suffixing systems (wh-)systems with increasing (unique) numbers (e.g. J12345 WH1, J122222 WH2). If a WH was deleted, the next WH could get its number.... 
#### My problems with your request:

1. The auto-renaming will definitely not be loved by everyone.
2. Reassigning a pre/suffix can be confusing with outdated bookmarks that still exists ingame.

If you find any more "pro"  arguments for this issue, we can keep talking about this request. If not, I´ll close this one.

**Comment by Kimeni** [comment]
If autonaming was a toggle you could enable/disable when you create a new map, it would satisfy both those with and without the desire to have it. Make it default to off.

And a simple WH followed by a ## is more than sufficient, any adjustments could be made manually, as they are now, but an automated system would ensure that systems are not giving duplicate names.

I would also add... We are here to use your amazing tool. We all had old systems with old ways we did things, change is good, change for the better is awesome. Just because all our groups had individual ways we handled naming conventions before, doesn't mean we should pass up a great feature because we can't be bothered to adapt to a new format.

 Autonaming is the #1 requested feature in our Corp. 

Same goes for the bookmark name generating suggestion, having something that expedites the process of exploring the chain by a few seconds when it comes to jumping holes and making bookmarks is a massive quality of life and time saver when you multiply it by hundreds and thousands. Which we get to pretty handily living in wormholes. 8)

As far as the bookmarks go, no real confusion - I am sure any WH entity has a system of bookmarking which includes folders for easy hole rolling and chain expanding, which means old bookmarks are not creating any confusion. And if they don't, they can definitely work one out.

**Comment by sNakiex** [comment]
I second this! We use the Vippy alias style where "home" would be 0 the static would be 1 e.t.c

Example:
![untitled](https://cloud.githubusercontent.com/assets/9659208/20650644/d7900806-b4d3-11e6-8286-18c35c252e2e.png)

**Comment by Slivo-fr** [comment]
We also use a renaming of this kind. 
I build a name list and I'm updating the database with the custom name every hour.
As pathfinder does not remove system with custom name from the data base (so far), we will open unamed WH less and less until it's all renamed.
I can share some details if you want me to

**Comment by lord-carlos** [comment]
We relay heavy on a similar feature when using vippy.
Vippy gives the first C5 system the name C5A, the next C5B and so on. NS_, LS_, HS_

Because it's predictable you can give a signature BM the correct name while scanning **before** you jump into them.

WH*X* would be the same. But if you remove WH1, WH2 should **NOT** be renamed!

![image](https://user-images.githubusercontent.com/155855/39408813-6cbfa1b6-4bdc-11e8-8686-3292daa1d9ff.png)

As you can see on this screenshot, you can both see the systemname, and the automated tag.
I don't care much about the name shame, but it should predictable, name should stay when others are deleted and indicate what class it is.

**Comment by lord-carlos** [comment]
Hey @exodus4d 
Would you be so kind and reevaluate this issue?

Not only makes it life easier for the scanner, but also later on.
"Lets meet up at c2a" is fast and clear communication. "Gang at J155737" will just increase human communication errors.

Maybe I'm missing something? I have a hard time understanding how to map without it.

**Comment by WildStrawberryEVE** [comment]
@sNakiex so when you want help in 5643 (C5->C6->C4->C3) you say you need ppl in 1132?
No thank you ;-)
That's one of most ridiculous chain naming conventions I've ever encountered :)

**Comment by sNakiex** [comment]
It actually makes sense if you have used vippy before, it only takes a few hours to get used to the naming convention and you'll never have duplicates.
Which a lot of the wormhole players probably used and/or still use.

**Comment by lord-carlos** [comment]
Was this closed by accident? Commit is about a broken persistent alias, this is a feature request about _automated_ alias.
_________________

How would people feel about a feature like this being implemented. Assuming it's possible to turn it of.

The exact naming scheme is not important right now, as long as the implementation has the following accept criteria:

* Predictable, not random. So you can bookmark a C5 with the right BM name before you jump in // before it gets mapped. 
* Keep the alias until system gets removed. 
* System name / J-Number should still  be visible.
