### ISSUE TITLE
[Enhancement] Simplification of statistics output

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#368]
Request: 
Statistic module (Great feature addition) is somewhat complicated for the reporting statistics. When looking at the values can you enable a way to remove the graphed values so only the sum total of the interactions are enabled. 

For output reporting this just makes the display much easier to present to the corp during meetings and for personal review. 

Perhaps a togglible simplified output to show in a columnized view of like the following if the CEO/leadership wants a quick reference for pilot activity. 
## | Pilotname  |  Wormholes scanned    |   Signatures scanned   |   Signatures updated  |

Confusion seems to be around the statics tracked, or atleast the level 
Can perhaps clarify the difference between the "systems" and "connections" values as normally you jump a to a new system and it would map a new connection automatically.

**Comment by exodus4d** [comment]
Thanks for your request 😄 ! Your request just fits the requirements your corp needs. This will probably not count for all groups out there. Adding more configuration options for columns is very complex, I had some problems with implementing that feature especially with the column configuration 😒.

But I have done some improvements to it, that might help you, even if it´s not 100% the way you want it. In the current version some columns get hide when resizing your browser. - The "**_sum_**" columns were added to that *minimized* table:

#### **Current** minimized table:
![stats_old](https://cloud.githubusercontent.com/assets/9299033/19820101/0c277146-9d58-11e6-929b-da65c4747c14.png)

#### **NEW** minimized table:
![stats_new](https://cloud.githubusercontent.com/assets/9299033/19820125/20a309f0-9d58-11e6-8681-6596dc7f854b.png)

****

But those _hidden_ columns are very helpful. Otherwise you can´t figure out those characters who just deleted stuff, and those who made the hard work with scanning (update/add)!

**Comment by Kimeni** [comment]
I'd also like to add, our corp incentives certain activities and having sum totals like this is something we're really looking forward to being able to track. We are very successfully using an honor system for reporting, but everyone would be happy if they didn't have to manually update their progress, and more uncertainty was removed!

**Comment by exodus4d** [comment]
@dnolen The current DB Schema is all based on "**weekly**" data. This can´t be changed. As by definition a year has **1** to **52 OR 53** _calendar weeks_. A *calendar week* does **not** start on the January 1. of a year. (e.g. 	January 3, 2016 is Week 53, 2015) -> [source](http://www.epochconverter.com/weeks/2016). 
So you are **not** be able to filter by month  (January 1. - January 31.). The current "_monthly_" filter filters the **current** week + the last 3 Weeks (4 Weeks).  

So what we _could_ do is some kind of "_range_" filter. Where a user can select **start** and ** end** week. But there are a lot more features planned to be added in "future" ("map filter", automatied statistics reports (mail), "leaderboard",....). But this can be discussed in new Issues 😄
