### ISSUE TITLE
[Feature Request] Always Show Current Location and Auto Tracking

### ISSUE THREAD

**Issue by NatuIi** [exodus4d/pathfinder#371]
When scanning k-space systems the map tends to get really cluttered when it tracks all stargate jumps when I only need to track workhole connections.  However, changing scope to wormholes disables the current location button and its basically impossible to select the current system to add signatures without creating clutter.  Could you make the current location always visible and clickable even for systems not currently on the map?  

Could you also add an auto tracking toggle so that the active system is always changed to the current location?

**Comment by dnolen** [comment]
@NatuIi  Where is this normally displayed? I just run with the scope set to wormholes only so I dont see it.  

If this could be something in the top menu, for example maybe spaced to the right of the active icon in the upper left hand side of the screen.

**Comment by NatuIi** [comment]
http://i.imgur.com/nRem3PE.png

top right of the menu bar.
It is only displayed when you are in a system already added to the map however in my situation I do mainly kspace scanning and I don't want every kspace gate to appear on the map, only wh connections.  Switching to the wormhole scope stops adding every kspace jump but then you cant select the current system to add/update signatures.  Just need an easier way to select the current system without having it appear on the map.

**Comment by exodus4d** [comment]
When a systems does not exists on a map, its data is not stored on the server and therefore you can´t _select/click_ on it. Selecting/editing a systems requires a stored system. Otherwise data get lost. 
Why do you want to edit data/signatures of a system that is **not** on a map? - I mean the sense of a mapping tool are visual/mapped systems?

But you are right, the "_current location_" should be visible even if it is not mapped (for consistency). The current location (if available) should now be permanent visible, If it is not mapped, the link becomes "_disabled_".

![test](https://cloud.githubusercontent.com/assets/9299033/19828702/c52c81ca-9dcd-11e6-9e32-e3466a212d5f.png)

> **Hint:** In case your current location is **not** already mapped, and you open the "_add system_" dialog, your current location should be pre-selected and ready to be added in *one click*.

**Comment by NatuIi** [comment]
> Why do you want to edit data/signatures of a system that is not on a map?
For people that primarily scan whs from k-space such as null sec alliances that use whs to third party and find connections.  There will be 10+ people scanning for whs covering multiple regions to specifically find wormholes only, so it makes things extremely efficient when you can pass over systems that have already been scanned and continue on.  With the current system the only way to update signatures of k-space systems is to keep the k-space system on the map but when you scan 3 regions only looking for whs it severely clutters everything.  

Setting the scope to wormholes fixes the clutter and only tracks wormhole connections but at the same time you cant update the signatures in a current k-space system without a wormhole as it wont be on the map.  My suggestion is to always allow signature edits to the current location regardless if it is visible on the map or not.
