### ISSUE TITLE
[Feature Request] Hide Anomolies in signature list.

### ISSUE THREAD

**Issue by Farlot** [exodus4d/pathfinder#376]
A function to hide anomolies.

Living in wormhole space you want to track anoms but dont need to see them in the signature list constantly.
A feature to hide them would be a welcome addition.

**Comment by exodus4d** [comment]
I added a new filter in 1.1.6 see: #349

**Comment by MorpheusXAUT** [comment]
Another suggestion, although I don't know if it's possible with the current way filters are set up:

Instead of having a dropdown select list that lets us choose one type of signature group, replace this with a list of checkboxes that allows us to select multiple groups we want to see.

Basically, I'd love to see data, relic, and wormhole sigs while I'm scanning a system, but have no use for the ore or combat sigs at that point. Once done scanning, I'd still like for pathfinder to track all sigs available (so I can see if anything disappears or new stuff spawns). A checkbox that lets you select multiple sig groups you want displayed would solve this perfectly 😄

**Comment by achehayl** [comment]
I would recommend the following options be available in the filter:

Gas
WH
Data
Relic
Combat
Sigs Only (Shows Gas, WH, Data, and Relic only)

**Comment by exodus4d** [comment]
#### Changes:
- new filter button added to "_signature table_" where users can set up their _default_ signatures shown in the signature table.
  - Multiple signature groups can be selected (e.g. "WH", "Combat", "Data",..) for filter
  - Filter data is stored persistent on the Client (IndexDB) per Character

#### Preview
![filter_test2](https://user-images.githubusercontent.com/9299033/43677374-44035c74-9801-11e8-9d92-04e8a2d3c27b.gif)
