### ISSUE TITLE
J005923 wrong static

### ISSUE THREAD

**Issue by segalws** [exodus4d/pathfinder#385]
Wrong static on wh J005923 http://www.ellatha.com/eve/WormholeSystemview.asp?key=005923
Please update sql: update system_wormhole set wormholeId=30 where id=83;
pathfinder.sql :
 ` (83, '2016-07-16 13:53:20', '2016-07-16 13:53:20', 31002534, 18),
  (84, '2016-07-16 13:53:20', '2016-07-16 13:53:20', 31002534, 59),
`
need:
` (83, '2016-07-16 13:53:20', '2016-07-16 13:53:20', 31002534, 30),
  (84, '2016-07-16 13:53:20', '2016-07-16 13:53:20', 31002534, 59),`

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
