### ISSUE TITLE
Redirection to homepage after login

### ISSUE THREAD

**Issue by husakja** [exodus4d/pathfinder#410]
Hello, when I log through EVE Authorization it redirects me back to the homepage. I couldn't even get to the map by www.[domain]/map. It also redirects me back to the homepage. Could you please advice me what am I doing wrong. Thanks.

**Comment by MorpheusXAUT** [comment]
I've had the same issue intermittently and had to click login one or two more times before I was finally able to fully log in.

One other thing I noticed (a user recently reported it): are you by any chance using IPv6 to connect to your server? I've had issues with proxy servers/IPv6 addresses since the database field for IP addresses was too short, as described in #407 

Do your PHP error or pathfinder CREST logs show anything while you're trying to log in?

**Comment by husakja** [comment]
#407 is already fixed. What bothers me is that I don't get any errors. It just redirects with no message at all.

**Comment by VivianMeally** [comment]
I have the same issue.

**Comment by atkinsj** [comment]
It's the login time variable set to 240 by default. If it's been 240
minutes since the initial login session, you'll select a character and it
will fail the login time rest but restart the timer--clicking it a second
then then works.
