### ISSUE TITLE
Corporation/alliance whitelists can be bypassed by browsing directly to /map

### ISSUE THREAD

**Issue by atkinsj** [exodus4d/pathfinder#414]
Reproducibility:

1. Login to Pathfinder
2. Change the corporation/alliance to add a whitelist
3. Go back to Pathfinder home page, see error as expected and cannot select character
4. Browse directly to /map

Their login is then valid until the cookie expired timer is up. Cookies should be expired immediately.

**Comment by exodus4d** [comment]
Thanks for this. Btw. Login is **not** valid until Cookie expire, it is just valid until you get automatically logged of by Pathfinder (which is 240min = 4h) -> Check `[PATHFINDER.TIMER]` section in `pathfinder.ini`.
But we should add a new check anyways.

**Comment by exodus4d** [comment]
I fixed this as part of #494, Corp/Ally whitelists is now checked for each request not only on character login.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
