### ISSUE TITLE
Right-click => add system in Firefox adds system in the top left corner

### ISSUE THREAD

**Issue by MilosRasic** [exodus4d/pathfinder#415]
Would be nice if it would add it on the spot where user right-clicked, like it does in Google Chrome. Not tested in other browsers.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
