### ISSUE TITLE
Added "realtime" map updates for active Clients (WebSocket)

### ISSUE THREAD

**Issue by exodus4d** [exodus4d/pathfinder#420]
#### What we need (v1.2.0):
In order to move away from the current Ajax "[long polling](https://www.pubnub.com/blog/2014-12-01-http-long-polling/)" for client maps, We need a new [optional] extension for Pathfinder -> A WebSocket Server that holds all active connections from all connected browsers and pushed new map data to all clients at once that have map access.

Slides about the new extension: 
https://docs.google.com/presentation/d/1GnS340uzfdhTjg4oGwxSCjr85PmOr7s3ConXJHEtWco/edit?usp=sharing

Repository: https://github.com/exodus4d/pathfinder_websocket

***

####  How it works?
1. As mentioned above, this extension is **optional** (but recommended) when ready. 
2. The new *WebSocket* server will run **beside** your current WebServer (Nginx/Apache) (check the slides above).
3. The WebSocket server must be started in order to accept new Client connections (read more about the [WebSocket HTML5 API)](https://developer.mozilla.org/de/docs/Web/API/WebSocket). Your Pathfinder installation will automatically try to connect to your WebSocket server. If everything is set up right, Clients will use the WebSocket server for map updates
4. When the WebSocket server shuts down, Clients will fall back to current "long polling"

***

#### New "health check" for WebSocket server on /setup page:

You will find a new section on the /setup page that shows you the current state of your WebSocket server (if it is online, if Pathfinder could connect to it, if clients could connect to it:

![ws1](https://cloud.githubusercontent.com/assets/9299033/21594106/e77debe0-d11e-11e6-835e-065505fccb0a.png)

***

#### New "Task manager" view (Clients)
The "task manager" gets some updates and got a new "Map sync" section that should give you some information about the map update technique for clients. Hint: The "WebSocket" Server connection is initiated within a [SharedWorker](https://developer.mozilla.org/de/docs/Web/API/SharedWorker) in the browser. Which is encapsulated from the rest of the webpage, in a new Javascript Thread. If a client get updates through your WebSocket Server, it looks something like this:

![ws2](https://cloud.githubusercontent.com/assets/9299033/21594210/19f440f0-d120-11e6-8b9a-b8a6aa5b3058.png)

**Comment by exodus4d** [comment]
"_TCP socket_" config and `CACHE` backend can be set by _PHP environment vars_

Updated: [develop-pathfinder.conf](https://gist.github.com/exodus4d/2b42057bb1b87990c0a17f704d22805f) 
^^ Config example for [_Redis_](https://redis.io/) cache backend.

**Comment by MorpheusXAUT** [comment]
Just a quick note (let me know if you want a separate issue on the [pathfinder_websocket](https://github.com/exodus4d/pathfinder_websocket) project):

I tried setting up a new instance of pathfinder v1.2.0 (commit f1bd647d8dd44ede751502cd4afb85278d04cdd0) and the latest pathfinder_websocket (commit [19bab3a](https://github.com/exodus4d/pathfinder_websocket/commit/19bab3ae5734dccd8a8c593b6bd38cc5cb5e9f40)) on GCP to play around with the websocket feature.
After some tinkering with all the setup and likewise, I was able to get it running properly, but noticed that - once a single client connected - the pathfinder_websocket cmd.php uses 100% CPU on one core, even if all clients disconnect.
Since I try to run pathfinder as small-scale as possible, I'm running single-core instances, so the websocket connections taking up 100% CPU basically hogs down all other resources such as the php app or nginx running on the same machine.

Is the websocket server actually simply this resource intensive? Or could there be a bug somewhere causing it to use too many resources?
I'd love to use the websocket version, but can't run it if it requires a "dedicated core" 😞 

I'll leave the test-instance up and running for now since I still have free credits on GCP, so if you want to log in and tinker with it, shoot me an email, happy to help.

Oh btw, I've shot you an email about a week ago about a Slack invite, would make discussing stuff like this way easier than on GitHub 😄

**Comment by exodus4d** [comment]
@MorpheusXAUT please resend a mail for your Slack invite, I haven´t seen it :( pathfinder@exodus4d.de

The high CPU load is a  known problem. We have already discussed it on Slack the last week. I haven´t found a solution for it yet and I can´t say if it is a problem on my side, or a "bug" in the framework I use... I need to investigate some time in it. But for now I don´t have any major problems with it, except the CPU thing...

**Comment by exodus4d** [comment]
I close this one. The initial task (implementation) is done

**Comment by MorpheusXAUT** [comment]
Alright, just sent you another email. If that didn't work either, just send one to the public email on my profile please 😄 
Glad to get into some testing regarding the high CPU issues as well if that's any help.
