### ISSUE TITLE
Mcrypt is deprecated in PHP7.1

### ISSUE THREAD

**Issue by oskari** [exodus4d/pathfinder#422]
#### Problem
According to [php docs](http://php.net/manual/en/function.mcrypt-create-iv.php) mcrypt is deprecated and will probably get removed eventually. 

#### Proposal:
Replace current usage of **mcrypt_get_iv_size()** and **mcrypt_create_iv()** functions with openssl functions **openssl_cipher_iv_length()** and **openssl_random_pseudo_bytes()**. If backwards compatibility is wanted to retain with using mcrypt on older php version, use **extension_loaded()** to check if mcrypt or openssl is loaded. [This is already done on the fat free framework itself](https://github.com/exodus4d/pathfinder/blob/c80db4d0141e2a987b43d0304e1c289e163fdf95/app/lib/bcrypt.php#L54)

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
