### ISSUE TITLE
[Bug] Statistics are no longer being updated since 2017

### ISSUE THREAD

**Issue by iryanclarke** [exodus4d/pathfinder#424]
![pathfinder error](https://cloud.githubusercontent.com/assets/5652496/22093136/3c829e2e-ddd1-11e6-9779-6e05d2046570.png)

As shown in the image above, our corp noticed that since January 1st, 2017, none of the signatures/connections/wormholes we add are being tracked by the statistics

**Comment by dkrotil** [comment]
Same here.

**Comment by exodus4d** [comment]
Agree. Ill fix it with the next release. The Log data is logged correctly and everything is finein the DB. It is just a UI problem.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
