### ISSUE TITLE
Recurrent logout

### ISSUE THREAD

**Issue by Slivo-fr** [exodus4d/pathfinder#444]
Hello there,

I'm using pathfinder 1.2 on a self hosted linux/apache/mysql setup.
After a while, I'm disconnected from pathfinder with a 403 error and the message "user not found"

I experienced this on another selfhosted setup with an older version of pathfinder.

Can I provide anything usefull log to help ?

**Comment by MorpheusXAUT** [comment]
I've had the same issue with a 1.1.7 instance, where pathfinder would log all my characters out at regular intervals.

Haven't seen this issue with 1.2.0 yet, however, with my old instance, it would also never "save" my login, thus requiring me to re-authorise against CCP's SSO every time I loaded the website. After the upgrade to 1.2.0, pathfinder appears to store sessions correctly and actually allows me to select one of my chars on the main page (instead of only displaying the login button).

@Slivo-fr does your instance save sessions/display chars for login properly? Might be it's something related to that...

Other than that: is there anything that looks remotely useful in any of the files in the `logs/` directory or your PHP error log (for nginx e.g. sometimes to be found in `/var/log/nginx/yoursite.error.log` or likewise)?

**Comment by Slivo-fr** [comment]
It does show my characters on the homepage yeah.

A got a bunch of following in crest.log
Sun, 19 Feb 2017 11:21:09 +0000 [109.88.212.167] Unable to find endpoint: location
Sun, 19 Feb 2017 15:09:12 +0000 [77.199.189.217] Unable to find endpoint: decode

error.log only have DT server down messages
others /logs file doesn't have anything suspect

Apache error log are also clear

**Comment by MorpheusXAUT** [comment]
Yeah, just as I've feared, seeing a similar situation on my side... The CREST logs are probably not really noteworthy since all CCP APIs have been really flaky over the last week(s), randomly returning errors or dropping endpoints...

I wasn't able to find a solution for this either, but can confirm it exists. I don't think I've seen one of these "logouts" since my upgrade so far, but I haven't used pathfinder as much as before either.

I'll try to do this myself if I think about it, but could you try to (at least roughly) time how long it takes until these logouts appear @Slivo-fr Maybe we can find a timespan that represent some session timeout or likewise, thus making the bug hunt easier.

**Comment by Slivo-fr** [comment]
It does take a while, maybe 2-3 hours ? I'll try to get a more precise estimation.

**Comment by Slivo-fr** [comment]
Here is what happens. I was AFK when it happens, I wasn't able to get the timespan
![image](https://cloud.githubusercontent.com/assets/10325988/23125810/e5731eda-f773-11e6-8cab-4fa0ef9ee69a.png)

**Comment by Slivo-fr** [comment]
Closed by mistake, my bad.
Keeps happening on a daily basis

**Comment by exodus4d** [comment]
@Slivo-fr Increase the max login time (default 4h) to what ever you want. ( 24h is max):

https://github.com/exodus4d/pathfinder/blob/master/app/pathfinder.ini#L104

It´s not a but, it´s a feature :)

**Comment by Slivo-fr** [comment]
Well, I'm trying this

However, even if it's a feature, it's pretty confusing:
- 403 popup on the map
- Redirect to home
- 403 popup again

A small lifting to make it more understandable would be great.

**Comment by Slivo-fr** [comment]
It still often happens with a LOGGED = 10080 (a week)
Sounds like there is something else
