### ISSUE TITLE
Maps disappear between logins

### ISSUE THREAD

**Issue by tmockler69** [exodus4d/pathfinder#448]
I check a WH system daily for sigs, and use pathfinder to track results and WH connections to Empire space.  On occasion, I will choose a character, and find that the previously created map has disappeared and the 'New Map' dialog box is automatically opened and prompting me to create a map.

**Comment by MorpheusXAUT** [comment]
pathfinder's maps have different "lifetimes", depending on the scope you created them for (private, corp or alliance), see [here](https://github.com/exodus4d/pathfinder/blob/master/app/pathfinder.ini#L62).

I assume you've created a "private" map and it was simply removed by the cron after the lifetime has expired. I'm actually not sure if being active resets that timer or if the map gets deleted after 14 days (per default) anyways since I've always used corp maps.

**Comment by exodus4d** [comment]
@MorpheusXAUT thanks for clarification. The `lifetime` was changed from `14`days to `30`days with the last release.
