### ISSUE TITLE
Use Wormhole Alias for in the "leads to" dropdown

### ISSUE THREAD

**Issue by Necrotex** [exodus4d/pathfinder#458]
It would be great if we could display the wormhole alias (if there is one) instead of the jcode  in the Dropdown "leads to" dropdown. Or maybe display both.

**Comment by Slivo-fr** [comment]
Agree :)

**Comment by exodus4d** [comment]
Is already implemented and will be shipped with v1.2.2.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
