### ISSUE TITLE
user Number overlay

### ISSUE THREAD

**Issue by NITSHEKORAY** [exodus4d/pathfinder#461]
![capture](https://cloud.githubusercontent.com/assets/26445734/23973178/4f404e34-09ab-11e7-9b4f-0eb24ebdf1a3.PNG)

whne system name on top of the grid number for the people count stays under and you can't really see when system is all the way up. Please fix if you can.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
