### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by mthomas92868** [exodus4d/pathfinder#464]
Hello When i go to http://www.thefinalresistance.net/pathfinder/setup i get

![image](https://cloud.githubusercontent.com/assets/7493521/24078542/8568fed2-0c2d-11e7-91db-dba89fc50188.png)
 
not sure

**Comment by dkrotil** [comment]
Register to Slack group, this is your setup problem not issue with PF.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
