### ISSUE TITLE
[Feature Request] Alternative layout left / right ( 60/40 Map / Data) split

### ISSUE THREAD

**Issue by Spurty007** [exodus4d/pathfinder#470]
I'd like to request an alternative layout 

Currently, the only layout available is an 'Over and Under' 75/25 (Map on top / data on bottom) split.

Request is for an alternative layout where we have a 60/40 (Map on left / data on right) split.

**Comment by Jazz-Pacaud** [comment]
Hi, thanks for this and for being very responsive to suggestions/concerns.  It would be good to be able to move the windows around...I am thinking about signatures on the right, resized and focussed map on the left and then system and routes below the map.  Cheers & Great work.

**Comment by exodus4d** [comment]
Just linking this Issue in here (related) [[Feature Request] Resizable areas #234](#234)

**Comment by moe-alabel** [comment]
It should be re-sizable by dragging like siggy

**Comment by Bluedagger21** [comment]
Is this still pending? I've seen #234 resolved, but besides just adjusting the size of the map, it still takes up an entire row and always the top row. A 60/40 split would still be in demand for myself (and apparently others).

**Comment by Bluedagger21** [comment]
@exodus4d just bumping this a bit, getting a lot more request/complaints about additional MAP window layout options.

**Comment by exodus4d** [comment]
@Bluedagger21 #234 was just about the persistent re-order of the "system modules" not about the hole layout.
The reason why this has not yet implemented is because I didn´t find an easy way without much work... I see **3** how it could be implemented, with increasing complexity:
1. The layout is already based on fix _breakpoints_ (browser window **width**). The easiest way would be a static 60/40 layout for browser > e.g. 1200px. Users would not get a chance to customize this. 
60/40 layouts don´t make sense on a mobile phone in portrait mode. 
2. Each user could choose between 2-3 predefined layouts.
3. Give full control to the users. e.g. drag&drop modules around and rearrange the layout to their needs. This would also require some kind "resizing" options to the map itself....

What do you think? - Keep in mind, that less complexity increases the chance of implementation ;)

**Comment by Bluedagger21** [comment]
Imo, don't give full control over map layout. I can imagine the headaches that could cause for you. Do provide maybe 2 or 3 templates of common requests. Then, like it is now, some windows are drag-able to fit in certain slots.

**Comment by exodus4d** [comment]
### New "custom layout" (v2.0)
I increased the max used screen space with and added some options for custom screen layout settings.

#### Settings:
- User can choose between a "**left**" and "**right**" base layout. (Smaller screens <1600px still get a more compact layout)
- Map modules can be activated or deactivated by their needs.
- Settings are stored and persistent.
  - Maps have their own layout settings 

![layout_shift](https://user-images.githubusercontent.com/9299033/73142244-d583b880-408c-11ea-91c9-6febcbb23028.gif)

#### More Drag&Drop:
- There are 3 drop areas, where modules can be placed at. Except the "signature" module (... which does not fit in smaller drop areas), all of them can be free moved around those areas and sorted within.
- Some areas have a fluid width (screen size depending) and modules change its layout based on its current drop area.
![layout_drag_module](https://user-images.githubusercontent.com/9299033/73142387-234cf080-408e-11ea-8863-43f7eb0bf3b2.gif)

#### Large screen layout:
On 4k sceens most of the available screen can be used now (fluid grid with)
![layout_large](https://user-images.githubusercontent.com/9299033/73142409-88084b00-408e-11ea-99a3-2fcbaf228880.png)
... and this demonstrates how the new layout looks on smaller screens (4k down to 400px width)...
![layout_responsive (1)](https://user-images.githubusercontent.com/9299033/73142574-a2dbbf00-4090-11ea-8fc4-a23b50909f4a.gif)

**Comment by mrurb** [comment]
Can we please change so that if there is no panels on the right side it takes the map to full size? My corp mates are going wild over the new change, as they can't have the map go full width.

**Comment by exodus4d** [comment]
@mrurb https://github.com/exodus4d/pathfinder/issues/935#issuecomment-614221168
