### ISSUE TITLE
"Access Denied - Character 'Char. Name' is Not Authorized to Login"

### ISSUE THREAD

**Issue by jperullas** [exodus4d/pathfinder#471]
So I'm trying to sign into pathfinder to find a damn Wormhole, and no matter what I do, I get "Access Denied - Character 'Char. Name' is Not Authorized to Login" every time. I've tried three different browsers, and have tried clearing my cookies + cache. Nothing works. I suspect it might be an issue with the EVE account itself, but I can't find anything to fix the issue. Any help would be great, thank you!
![capture](https://cloud.githubusercontent.com/assets/26950224/24736799/4e6cc920-1a58-11e7-8600-308821ef4fcd.JPG)

**Comment by MorpheusXAUT** [comment]
Are you using the official (hosted) pathfinder or running your own instance?

**Comment by jperullas** [comment]
I'm running it from the official website, so I suppose it would be the first one you mentioned.

**Comment by kaysix87** [comment]
I also have this issue and I havn't found any solutions so far

**Comment by jperullas** [comment]
Same here, been dealing with this for the past two weeks. Nothing has worked, unfortunately.

**Comment by dkrotil** [comment]
Just wait for new PF version, there will be switch to ESI, maybe this will solve your problem.

**Comment by dkrotil** [comment]
Hehe I´m getting same error as you now.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
