### ISSUE TITLE
[Feature Request]Display Ship Name

### ISSUE THREAD

**Issue by Ordo-Vhett** [exodus4d/pathfinder#487]
![image](https://cloud.githubusercontent.com/assets/28077119/25599290/04dc0964-2ea9-11e7-9e7e-bb56fd3de2b5.png)

I am in a Tengu named "Imicus" instead of having the (?) hoverover display the ship name can we get column just for ship name. This will help us wormholers identify ships on d-scan as friendly or hostile

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
