### ISSUE TITLE
[Bug] 1.2.2 WH "leads to" 1.2.1 Feature

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#488]
Hi,
Since I upgrade from 1.2.1 to 1.2.2, WH "leads to" feature does not work. WH list is not updated with wh linked to the system.
Thanks.

**Comment by Kyrithis** [comment]
I concur. The "leads to" drop-down in the signatures comes up completely blank, though there appear to be placeholders for the systems you can select.

**Comment by Ordo-Vhett** [comment]
it will only list the system name ALIAS

**Comment by DLB82** [comment]
Thanks for the tips. So, define an alias is now mandatory to use "leads to" list.
In 1.2.1, the default alias is the system name and the system name is in the "leads to" list.

So the feature "leads to" can be inprove to have in the list the system name if the alias is empty (not define).

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
