### ISSUE TITLE
[Enhancement, Help needed] Add parsing for german, french and other languages.

### ISSUE THREAD

**Issue by Kill4Free** [exodus4d/pathfinder#490]
Hello,

it would be cool if some people could help me with other language translations for parsing.
The current Pull Request #475 adds german and french for signature type.

Mfg Kill4Free

**Comment by OmniarchIO** [comment]
I can help with Simplified Chinese translation. (actually did it before via changing source code on my own server)

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
