### ISSUE TITLE
Restrict login to specific corporations/alliances doesn't work very well in 1.2.3

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#499]
Hi,

Since 1.2.3 installation, restricted login to specific corporations/alliances does not work.
I have the message : "Access denied Character "XXX" is not authorized to log in. Reason: failed to match alliance whitelist"

I have just corporation added in "pathfinder.ini".  I try to add my alliance reference but it doesn't work too.

The unique solution is to remove all restricted access.

Thanks for your help.

**Comment by exodus4d** [comment]
This is a bug :( I fixed it recently:

https://github.com/exodus4d/pathfinder/commit/9cfc032440ae641698bdec9f03ccad81a3fbe860

**Comment by ddouglas493** [comment]
I to am receiving this error message. Would it hurt to manually modify the code? Will it break the update when 1.2.4 is released?

**Comment by exodus4d** [comment]
No you can manually edit the code just keep in mind, to replace the file with the newer version when 1.2.4 will be released. If you use `git pull` for updated, this will *not* overwrite your local changes you made. This could lead to problems.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
