### ISSUE TITLE
501 Error on login

### ISSUE THREAD

**Issue by BaronNox** [exodus4d/pathfinder#523]
I'm getting the following error upon login:
http://imgur.com/YfEz0Pm

Everthing worked fine but 2 or 3 days ago the tracking stopped working.
Today I tried to relog but I'm getting this error now.

**Comment by Ordo-Vhett** [comment]
CCP changed Universe/names endpoint to return a 501 error where previously it returned 404. Pathfinder apparently ignores but still reports to Log 404 errors but hard stops 501's

**Comment by Ordo-Vhett** [comment]
temp work around: edit controller.php /app/main/controller/controller.php
remove die()  command from error reporting (highlighted in Picture below)
![image](https://user-images.githubusercontent.com/28077119/29645220-0bb4ad36-884a-11e7-9ba2-70e8156981fe.png)
and save this will stop the 501 error but a backup should be made prior to editing so that you can revert once universe/names endpoint is back online

**Comment by BaronNox** [comment]
I tried logging in today again and it worked. Seems to be fixed. Thank you.

**Comment by generalluser** [comment]
The 501 Error on login is still occurring for me. Thank you for the workaround - I'll try that
