### ISSUE TITLE
[Enhancement] create new signature-ID when jumping into a new system

### ISSUE THREAD

**Issue by bandit420** [exodus4d/pathfinder#526]
When jumping into a new system with activated tracking it would be nice to create a new signature automatically in that system.

One example:
* jumping from C2 D382 to new WH -> create a bookmark with the same ID (e.g. ??1), type Wormhole, and connection where you came from (and maybe a K162 if it is a exit, the other way around is guessing)

BTW wanted to say a great tool, thanks for your effort.

**Comment by Bluedagger21** [comment]
Resurrecting this issue. This would be very handy, even if dumbed down some. A nice QoL change here would be to simply detect when jumping into/out of a wormhole and thus add a new wormhole signature in the newly created destination system. This would only happen if the system does not already exist in the map and thus ONLY on creation. We don't even really need a K162 type as I imagine that would add in a lot more checking.

**Comment by exodus4d** [comment]
@bandit420 I think you mixed 2 requests in here :)
1. "create new bookmark" inside the EVE-client is currently not possible. _ESI_ only supports **read** `GET` endpoints: https://esi.evetech.net/ui/#/Bookmarks
2. create a new signature-ID inside your "target" system is not a big task. The "problem" here is, that you still have to set the signature name manually. Without a name a signature-id would be useless for others. There could be only  auto-set the type "wormhole", and its destination system (the system you came from), but that information is also visual at the map.

**Comment by bandit420** [comment]
All right, if there is only a read endpoint, that is understandable.

If I remember correctly, it was just about somehow smoothen the process when jumping into a new WH that does not yet exist in Pathfinder.

This is represented for me by the function "Autoselect current location", since there is a connection generated and the rest can be mapped manually.

From my perspective the topic could be closed, because I can not estimate what possibilities the EVE-API still offers (not a programmer, just a operator/user).

**Comment by exodus4d** [comment]
Yeah, there are good reasons _CCP_ don´t have a public **write** endpoint for bookmarks. It would be quite easy for a 3rd party took like _Pathfinder_ to _auto set_ bookmarks for long travel distances by avoiding PvP. You could use e.g. zKillboards API to check each system on the road for recent kills and avoid those systems.
In addition each bookmark has its own x/y/z coordinate in space, if you could set bookmarks from "outside" the client, you could easy calc "warp in" bookmarks for gates/stations because its coordinates are pubic available.

Take a look at #812 and the new "jump history" _breadcrumb navigation_, released next weekend. If _PF_ detects a system change (jump) you can either click previous systems to select (if they are already on the map), or add them.
