### ISSUE TITLE
Feature Request Mark Connection Size

### ISSUE THREAD

**Issue by BluePatriot** [exodus4d/pathfinder#568]
Hello,

It would be nice to have wormhole connections also possible with other size classes.

Frigate = 5,000,000 t
Cruiser = 20,000,000 t

currently only frig mark is possible

**Comment by CalMatar** [comment]
It would be nice to have what are labeled as Medium Holes (Cruiser) and the Capital Holes (Very Large) since the majority of holes are Large they don't need any kind of designation, even though there are many different sizes of them they are still only Battleship size. 
Thank you

**Comment by exodus4d** [comment]
I think it is even more "complex": 
If a connection is linked to a signature, that has specified a `type` ( eg "I182") we know exactly that it must be a  -> C2 hole wich 300.000t max jump mass.
So the feature we are talking about is to mark a connection  with a "size" label, before someone figures out the exact label for it (e.g. if you are sitting on a K162 end of a wh). If a signature type gets linked to it, and we have the exact label, the previous "small"/"med"/"large" flag should be overwritten, right?
Do you think about a "context menu" entry for signatures for the labeling?

**Comment by BluePatriot** [comment]
no i mean the context menu, the is it possible to set the frigate hole connection visible with color in map, nice to have for cruiser size connections too

**Comment by CalMatar** [comment]
I agree but to add capital holes to the pattern/color code so you would have "special" pattern/color codes for frigate holes (already there), cruiser holes, and capital holes.

**Comment by exodus4d** [comment]
@CalMatar agree! 
I´m about to start with the implementation for this feature. There are still some _design aspects_ where I need some proposals for:

There are **4** mass levels a user could choose from, for a connection:

| Type | Text           | UI (color/label/...)  |
| -------------: |-------------| -----:|
| S | Only the smallest ships can pass | orange (bubble line + "frig" label) |
| M | Up to medium size ships can pass |  ???  |
| L | Larger ships can pass | ??? |
| XL | Very large ships can pass | ??? |

Just focusing on **colors** only will probably not work this could make the map less readable. So we should use a combination of color + label? - or change the stroke to "bubble"/"dashed"/...?
We could use gradient background colors, or colored shadows,.. maybe animations?
What would you take?

We could also make an _alternative_ map view, like the "EOL timers" that toggle the current map view into a "_mass map view_", maybe on "hover"?

**Comment by CalMatar** [comment]
As I said previously you don't need to do anything for the "standard" large holes and leave them as they are. As for the other two there should be options similar to the existing one for the small hole just different colors and patterns to represent the other two sizes.
Hope this helps.

**Comment by exodus4d** [comment]
Colors will not work: Imagine an "**EOL**" (pink outline) wormhole that is marked as "**reduced**" (orange color) now becomes marked as "**size M**". - Where to apply the 3rd color for "**size M**"?

My approach was to add (colored)-labels for the size (if set). "Frigat" marked connections would become size "S".
![kzVsVI3](https://user-images.githubusercontent.com/9299033/59110600-c4d8d380-893f-11e9-836e-fcc9c4ecb3a3.png)

**Comment by exodus4d** [comment]
Maybe a different shape + overlay ...
![9fiKfMY](https://user-images.githubusercontent.com/9299033/59114443-7596a100-8947-11e9-9874-479bd5d7c012.png)
... or different shape + color + overlay?
![RwXzfse](https://user-images.githubusercontent.com/9299033/59114457-7deedc00-8947-11e9-82e3-89be4b17777f.png)

**Comment by CalMatar** [comment]
That would work but I would leave the one for the Large hole the same as it is currently since it is the most common size hole and modify the XL hole to be the long broken but otherwise I think this is a good way to do this. It clears things up and makes them a lot easier to easily see the type of hole on the map. The only think is can you make the icons just a slight bit bigger please. Some of us (meaning me if no one else) has trouble seeing those small icons on my laptop screen sometimes especially since I can not zoom the map without messing up my whole browser (and don't get me started on the scrolling in the map peave that is for another thread). 
Thanks.

**Comment by CalMatar** [comment]
@exodus4d one other thing I was thinking of today and I am not sure how much of a pain it will be to do if it is even possible but I just thought I would add this idea to the mix. You have a list of every wormhole ID in the game and what size they are. Could you not automatically make the connections "change" to the correct hole configuration, with the exception of the K162 of course, depending on what the signature of the hole is since you already have that information available to you? Again, I am not sure how much more of a problem it would cause to do this that way but it is a possibility especially since all of the information is available on the size of each wormhole signature.
Thanks.

**Comment by exodus4d** [comment]
Yes that is the plan. See my comment here https://github.com/exodus4d/pathfinder/issues/645#issuecomment-417924275 . You can manually label a wh to size **S** to **XL** (e.g. if you just know the K162 end of a hole). If that hole gets mapped from the signature panel from either _source_ or _target_ system, we know the _real_ name e.g. N968 this "overwrites" previously set size flag.

WIP: The wormhole table already got a new "**size**" column:
![B8mKymT](https://user-images.githubusercontent.com/9299033/59142934-e67c9e00-89c5-11e9-8740-1167337fac1f.png)

WIP: New options for "Size" added to the connection´s context menu:
![pUJkTAT](https://user-images.githubusercontent.com/9299033/59142952-08762080-89c6-11e9-85e4-28ee8480a34d.png)
 
WIP: And the current state of the 4 wormhole sizes:
![Gw10aJS](https://user-images.githubusercontent.com/9299033/59142960-204da480-89c6-11e9-9901-10e57714e787.png)
 
- **S:** Reduced path with (-2px)
- **M:** No changes to path with. Longer outline dashes.
- **L:** No changes to path with (no UI changes at all)
- **XL:** Increased path with (+2px)

**Comment by exodus4d** [comment]
1. I removed the color codes from the new "*size*" labels, because it makes the map harder to read, and most of the colors codes are already in use with a different meaning (e.g. blue ≙ C1-C2 wormhole names)

2. The *size* (S, M, L, XL)  of a WH now changes automatic if a signature gets mapped to it...
![auto_change_wh_size2](https://user-images.githubusercontent.com/9299033/59564592-e2492400-9048-11e9-8e6c-fcd24fbed419.gif)

3. You can manually set the size of a WH connection as long as it is *not* mapped to a signature that specifies the size of the wormhole....
![disabled_change_wh_size](https://user-images.githubusercontent.com/9299033/59564598-f0974000-9048-11e9-862b-a11b13ccf19d.gif)

4. New "*size*" labels added to _routes finder_ module
![UhVBkGD](https://user-images.githubusercontent.com/9299033/59564645-87fc9300-9049-11e9-80ea-0d283ba60299.png)

5. New "*size*" labels added to wormhole info tooltips
![az4DBHq](https://user-images.githubusercontent.com/9299033/59564655-9ea2ea00-9049-11e9-9f9b-b4b9e349b5f0.png)

6. Updated _manual_ with new wormhole size information
![6FWltKu](https://user-images.githubusercontent.com/9299033/59564664-bb3f2200-9049-11e9-826e-f76113ce6b0f.png)

**Comment by CalMatar** [comment]
@exodus4d when is the update supposed to be rolled out on the public server?

**Comment by CalMatar** [comment]
@exodus4d Thanks for the update. I am getting a repeating error 500 when I logged in and it keeps restarting and giving me the same error and then when I click OK it restarts and gives the error again.

**Comment by CalMatar** [comment]
@exodus4d, I have a question on this. If I have a WH connection that is an E175 in my WH and I mark it thus in the connection list and mark the connection hole it goes to in the list then the map should automatically mark the connection as the corresponding size and connection (E175) per the example above is this correct?
