### ISSUE TITLE
Possible integer overflow when dealing with wormhole mass >2.147m tons

### ISSUE THREAD

**Issue by kvolakos** [exodus4d/pathfinder#577]
While playing around with the mass tracking functionality of Pathfinder, I noticed an issue with the total mass displayed particularly on the K346 type wormhole, which should have a mass of 3 million tons +/- 10%. Pathfinder displays the total mass of the wormhole as 2,147,483,647 tons, as seen here:

![image](https://user-images.githubusercontent.com/31253412/35179751-5afcc876-fd6e-11e7-9e73-5b510c85359f.png)

I'm assuming there's some kind of integer overflow or type error here. Can confirm this is reproducible at least with K346-type holes of ~3m mass, haven't been able to try with other wormhole types of similar size or greater yet.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
