### ISSUE TITLE
Discord ptb.discordapp.com

### ISSUE THREAD

**Issue by MyUncleSam** [exodus4d/pathfinder#578]
Hi there,

I tested the new discord feature and it seem to work fine. There is just one thing which made configuring it a little bit complicating:

If you are using the discord app for windows (not the webbrowser), the webhook always points to https://ptb.discordapp.com/api/webhooks/XXX/XXX (subdomain "ptb").
But pathfinder only accepts urls starting with https://discordapp.com/ - so I was wondering how I should configure that. So I loaded the web client using my browser and did exactly the same as I did inside the windows application. And it generated the url as needed without the "ptb" subdomain. I checked this twice, even if you added in one application a webhook the webbrowser is not prefixing the "ptb" suburl but the windows client does.

So my question is:
Can you add to the allowed list the "https://ptb.discordapp.com/" too? I accessed the urls to the api with and without this subdomain and it returned exactly the same.

PS: it seems like it is doing that because I am using the public test build - ptb.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
