### ISSUE TITLE
Wrong website after login.

### ISSUE THREAD

**Issue by romsas** [exodus4d/pathfinder#621]
Pathfinder is working perfect, but after i login to it, pathfinder redirects me to a wrong link http://_/map*  . But if i manually add my IP instead of „_“ It works fine. I‘ve tried looking in files, but could not find anything :/ Also maybe it gives me error because i don‘t have domain?

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
