### ISSUE TITLE
IIS support

### ISSUE THREAD

**Issue by webba** [exodus4d/pathfinder#635]
I know that pathfinder states it is intended for nginx or apache however it runs fine on iis with the exception of the cron job which is due to a slight difference in syntax between cmd and bash,

I resolved this for myself by taking the windows detection from app/lib/base.php and adding it to app/lib/cron.php and a slightly different exec statement and I also added a basic web.config file, see https://github.com/exodus4d/pathfinder/compare/master...webba:windows

I'm unsure if the cron.php is something you have written yourself or is part of an external library but I will happily submit a pull request if this is applicable.

**Comment by exodus4d** [comment]
Hi @webba ,  Nice to her, you got _PF_ working on ISS :) I never have tried that before.

The cron.php is a 3rd party plugin for _F3_ framework: https://github.com/xfra35/f3-cron which is not written by me.
I just checked the repo and figured out the version I use is 3years old and there were many changes made in the meantime, including a "Windows detection" see:
https://github.com/xfra35/f3-cron/blob/master/lib/cron.php#L122

You should be able to update the plugin to the latest version and let me know if this solve your issue. I´ll do some tests as well with Nginx and update to the latest version of cron.php .

**Comment by webba** [comment]
Just updated ours on IIS to the version linked works fine and solves the issue.

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
