### ISSUE TITLE
Dotlan link uses spaces rather then underscore

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#638]
The dotlan link should be using underscore instead of space as `http://evemaps.dotlan.net/map/Sinq%20Laison/Doussivitte` returns "Map 'Sinq Laison' could not be found"
and it should be
`http://evemaps.dotlan.net/map/Sinq_Laison/Doussivitte`

**Comment by mrurb** [comment]
After a further look at dotlan it turns out that it uses underscore for regions and spaces for systems

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
