### ISSUE TITLE
Intel module - can't add 2 structures of the same group but with a different type

### ISSUE THREAD

**Issue by DLB82** [exodus4d/pathfinder#640]
Hi,

Before describe this issue, I try to remove and rebuild "pathfinder" database and "eve_universe" database.

The issue :
I can only add 1 type of structure by group. Example: I can add Fortizar but not Astrahus or Keepstar. I can add Athanor but not Tatara.
![structure pb](https://user-images.githubusercontent.com/24720730/41506719-739ea212-7223-11e8-8a31-63d9a09fcd4f.png)

I check "eve_universe" database and I have other type of structure for a specific group. It's really strange.

I don't know if it's a bug or an issue when I reinit databases.

Can you help me, please?
Thanks a lot.

**Comment by exodus4d** [comment]
Please check the `initData` Ajax call on /map view for `universeCategories` if you can find them here. 
If you can´t see all other options, -> clear Cache (or _Redis_ if you use this as Cache backend). 
All stuff from the `initData` request is _static data_ that will not change that often. 
The `initData` response is cached for 1h.

![ugfu9jx](https://user-images.githubusercontent.com/9299033/41506843-cd0c5acc-7225-11e8-94f3-e714e2963c75.png)

**Comment by DLB82** [comment]
I just wait and now I see other structures but not all of them. I don't know if it's normal.

For example, I don't see : 
- Upwell Paladine Keepstar
- Prometeus, Horizon, Dracous and Moreau  Fortizar

Is that normal?

**Comment by exodus4d** [comment]
@DLB82 it looks like I found a bug that could be related to the behavior you described. Should be fixed in the next release

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
