### ISSUE TITLE
[Feature] Add Medium connection flag for Med WH

### ISSUE THREAD

**Issue by Ordo-Vhett** [exodus4d/pathfinder#645]
Can we add a connection flag similar to the one that marks frig holes to add a visual reference of Mass restriction along a route.

**Comment by Carson2006** [comment]
Literally the only addition I've ever wanted to add to this application.

I do have some experience with PHP, so I may look into doing this myself as a PR.

**Comment by Slivo-fr** [comment]
Well, I may be wrong but ... isn't that only and always wormhole from or to C1 systems ? 
If that's the case, I don't really see a need for this

**Comment by exodus4d** [comment]
I think he is talking about e.g. K162 holes you scanned down. When you open the description you see something like "smaller ships", "larger ships", "largest ships". So for the time the source system is unknown and the WH type (e.g. A239) is not mapped yet which would give you the exact mass for that hole. 

I plan to make it a bit more "flexible", If a Signature is mapped to a wormhole -> We don´t need that information manually added because we already know the mass. -> I want to add a "filter" where e.g.  connections can be filtered by "Battleship size", "capital ship size"....
For the time a wormhole is **not** mapped to a signature we could use some kind of new "connection flag" you are talking about.

Not 100% sure how we could do this. I´m open for any ideas.
