### ISSUE TITLE
php version not satisfied

### ISSUE THREAD

**Issue by razaqq** [exodus4d/pathfinder#683]
getting

  Problem 1
    - This package requires php-64bit >=7.0 but your PHP version (7.0.30-0+deb9u1) does not satisfy that requirement.
  Problem 2
    - Installation request for exodus4d/pathfinder_esi dev-master#v1.2.5 -> satisfiable by exodus4d/pathfinder_esi[dev-master].
    - exodus4d/pathfinder_esi dev-master requires php-64bit >=7.0 -> your PHP version (7.0.30-0+deb9u1) does not satisfy that requirement.

Im on debian 9 armhf 32 bit

**Comment by dkrotil** [comment]
Installation issues doesn´t belong to Github, register to Slack and try to find answer there.

**Comment by razaqq** [comment]
why the hell would uncompiled php code require 64 bit tho

**Comment by exodus4d** [comment]
@razaqq Version requirements for e.g. PHP are set in `composer.json`.  
They package versions in there _might not_ always represent the _real_ minimum version of a package. 
This is because I can not provide tests for each version available. If your server setup matches all the requirements from `composer.json` you should be save because it was tested. If not and there is no option for upgrade, feel free to adjust `composer.json` with your installed versions and give it a try.

If you can´t see any problem with your package, please let me know and we could adjust the `composer.json`

**Comment by razaqq** [comment]
alright giving it a try by editing the version in composer.json
