### ISSUE TITLE
Public: Signature reader: Update Signatures button does not submit

### ISSUE THREAD

**Issue by andrewd18** [exodus4d/pathfinder#691]
When I open the signature reader, paste in signatures and click **update signatures**,
Then the dialog does not disappear and the signatures are not updated.

I have logged out and back in and performed a complete refresh of the page. No change.

**Comment by aalfath** [comment]
I am having the same problem. The **update signatures** button does nothing.

**Comment by cwalker94** [comment]
Maybe this is what was going on with issue #690? I've asked for more details with that issue...

**Comment by CalMatar** [comment]
I have been trying unsuccessfully to get my data to submit since you did the update this morning. Once I found out where you moved the buttons to 
I click the Signature Reader Icon.
I do a ctrl  + v to paste into the box and click on the lazy delete to remove old items
I then click on the 'update signatures' box and it highlights but does nothing else. No other indications that I even clicked the button. It is though the onclick command is not registering. (no I am not using a local version I am using your hosted version on the website.)
I did not get a chance to update signatures yesterday so this might have been a problem yesterday as well. 

![signature reader](https://user-images.githubusercontent.com/42744905/46221897-ba7c2980-c31c-11e8-83f9-adeb6db52c55.jpg)

**Comment by CalMatar** [comment]
I tried to update signatures again today and I got the following error on the console:
 [Show/hide message details.] TypeError: i is undefined[Learn More] system_signature.js:151
[Show/hide message details.] TypeError: i is undefined[Learn More]
system_signature.js:151
[Show/hide message details.] TypeError: i is undefined[Learn More] system_signature.js:151
[Show/hide message details.] TypeError: i is undefined[Learn More] system_signature.js:151

**Comment by exodus4d** [comment]
@CalMatar @Carson2006 My public installation is updated with the hotfix. 
You probably need to clear browser cache and refresh page
