### ISSUE TITLE
Contextual menu CSS glitch

### ISSUE THREAD

**Issue by Slivo-fr** [exodus4d/pathfinder#693]
There is a small misplacement on firefox 62.0.2 x64, see bellow :

![image](https://user-images.githubusercontent.com/10325988/46136454-eda0b900-c247-11e8-8bc7-1a5e7dff2ba5.png)
![image](https://user-images.githubusercontent.com/10325988/46136525-188b0d00-c248-11e8-8afc-7ea780b5a9ff.png)

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: Please reopen/comment this, if you have problems/questions about it.

***
*Auto-generated response*
