### ISSUE TITLE
Userdir URI install issues

### ISSUE THREAD

**Issue by brutalhum** [exodus4d/pathfinder#706]
Hi,

When I install Pathfinder on a non-root path, namely a userdir's subdirectory, hence something like "https://some.domain/~adude/pthfndr/", even if BASE is correctly set in environment.ini, some things don't work, like SSO links on the landing page.

Effectively, the EVE SSO button on the landing page bears a href link to /sso/requestAuthorization ... even if there can't be any relation to that path with anything sitting in the userdir subdirectory.

BASE does get read though when forming other URLs elsewhere.

I've tried setting PF-ENV-BASE and other environment variables in apache's configuration, see if it helped, but then the 500 error regarding null data instead of string typed data came up.

Thanks in advance for helping, I'm out of ideas ^^

**Comment by GT4** [comment]
Hello.

I have the same issue. An install in a subdirectory (in my case /pathfinder/ ) instead of webroot. Only difference is i use Lighttpd instead of Apache.

Some links get constructed without {{ @BASE }} or are hardcoded maybe ? So they are invalid (example: for setup it wants me to go to /setup instead of /pathfinder/setup) . If i access the urls manually they work to some extend. I'd think the url contruction issue is also why i cannot create the tables on the setuppage.

I've attached my environment.ini, my serversnippet for Lighttpd, the html output for if i open pathfinder, and from the setuppage. 

[environment.ini.txt](https://github.com/exodus4d/pathfinder/files/2530441/environment.ini.txt)
[lighttpd.conf.txt](https://github.com/exodus4d/pathfinder/files/2530431/lighttpd.conf.txt)
[Pathfinder.htm.txt](https://github.com/exodus4d/pathfinder/files/2530432/Pathfinder.htm.txt)
[Setup.htm.txt](https://github.com/exodus4d/pathfinder/files/2530433/Setup.htm.txt)

Ps: While looking around for a bit in the template files i noticed some slashes are wrong or missing ? F.ex https://github.com/exodus4d/pathfinder/blob/edf264edea534ae6ba8d7f212c6a14f9ba85b862/public/templates/view/index.html#L25 needs a / beetween the }}{{

**Comment by exodus4d** [comment]
Thanks for your report! I have not tested subDir installation for a while and had to figure out how it works on _Nginx_. 
I fixed the broken routes/links for subDir installations in the commits above. 

I made a new [wiki: Nginx-subdir ](https://github.com/exodus4d/pathfinder/wiki/Nginx-subdir) with my example config. Be prepared, looks a bit _complex_. If someone has a better solution, let me know.

**Comment by brutalhum** [comment]
Thank you very much for taking this into account :)

I'll test it asap and come back to you if I run into any issue (or if I find anything else worth mentioning).
