### ISSUE TITLE
"Shattered Systems" should be supported

### ISSUE THREAD

**Issue by Beaudidly** [exodus4d/pathfinder#72]
I'm in a c13 and I can't select q003 or any other wormhole types other than a k162 for listing it in the signatures section.

**Comment by exodus4d** [comment]
Thanks for reporting! Ill check it. This might be fixed with #66

**Comment by exodus4d** [comment]
Thanks for reporting! :)

##### Added support for "Shattered Systems"

- C13 Holes are in fact "new" shattered systems (wormholes)
- Shattered Systems got a new map symbol (**SH**) and a new color (indigo): (check screenshot)
- The static wormholes of "shattered systems" are not completely known. There is a *Project* ongoing: http://wiki.eveuniversity.org/Project_Reassembly/List_of_Shattered_Systems
- I added all the known static WHs to the dropdown, plus all known frigate holes (check screenshot)
- I added a "Shattered system" information to the system info table, because the statics are not available for now. (check screenshot)

![shattered](https://cloud.githubusercontent.com/assets/9299033/11226782/67859374-8d82-11e5-964f-151d26d1ff81.png)

**Comment by Calavoow** [comment]
@exodus4d note that there are also shattered wormholes which aren't C13s, so the `SH` designation may be ambiguous.
