### ISSUE TITLE
Rally point notification only for w-space

### ISSUE THREAD

**Issue by daschalki** [exodus4d/pathfinder#733]
Hello!

I was just about to configure rally point notifications to get our discord users pinged - although we noticed that these notifications are not sent when a rally point is in k-space.

Is that working as intended? Any possibility to get k-space notifications working too?

Thank you,
daschalki

**Comment by exodus4d** [comment]
This works on my side. Set rally point in "Amarr" with a configured webHook URL for Discord pokes.
https://i.imgur.com/Yxnnhvd.png

Any more information? maybe the system name? map type?

**Comment by daschalki** [comment]
Hello, thanks for your reply!

Double checked with your official installation - worked great, just not with ours.

Tried several systems, doesnt matter if highsec lowsec or null, everything thats not w-space doesnt work.
No errors in the log.

Any perequesites for these webhooks I might have possibly missed?

**Comment by exodus4d** [comment]
hm no, there is no difference between w-space and k-space pokes. 
Is the issue maybe related to the system name, system description?

**Comment by daschalki** [comment]
It acutally seems to be a map specific issue - I built another map with same settings and the same webhook, identical scope and sharing (corp map), added the same systems - rally point works.

We're just gonna live with it, Ill try to export and re-import the map sometime.

Thanks for your time.

**Comment by csatlos** [comment]
I was also running into this issue and seem to have found the trigger, though admit I don't quite understand the real reason for the issue. After capturing requests to a dummy server and looking at the JSON being sent by Pathfinder, the culprit is the "TrueSec" value of the system. I also noticed during testing that the app uses the Slack-compatible Discord webhook in the background.

When the TrueSec value is an integer (ex. -1 for WH space or 1.0 for some HS systems), it seems to work OK. But when the TrueSec value is a decimal, the call to the Discord Webhook fails with HTTP 400. Changing the numerical TrueSec value to a string (ex. "0.8" instead of 0.8) seems to be a workaround.

My solution is not elegant, but I solved it temporarily by forcing the field to be formatted when the embed is created. This was done by editing [AbstractRallyWebhookHandler.php Line 98](https://github.com/exodus4d/pathfinder/blob/62dc991760e3d0bfde078affde20a3fcc6ed2360/app/Lib/Logging/Handler/AbstractRallyWebhookHandler.php#L98) and setting the format parameter to 'true'.
`$attachment['fields'][] = $this->generateAttachmentField('TrueSec', $objectData['objTrueSec'], true);`
