### ISSUE TITLE
Alias box closing

### ISSUE THREAD

**Issue by webba** [exodus4d/pathfinder#774]
The alias box closes when highlighting text if you release left mouse button when the cursor is outside the alias box. This can be a little annoying as when renaming it is often quicker to drag quickly to highlight all and you can easily go past the end of the alias box.

Steps to reproduce:

1. Double click on a system to show the alias text box
2. Click and drag from any point in the text box past either edge
3. Release the mouse and the text box hides

**Comment by pezz** [comment]
Heh, I don't know if this is related, but I've found that sometimes when you double click to rename a system, type the name, hit enter.... Nothing happens - the system name stays the same and you have to re-do the process.

It's like what happens when renaming bookmarks in EVE sometimes heh.

**Comment by exodus4d** [comment]
I get your point. The problem here is, that all the "_in place editing_" (system alias, signature table cells,..) is a 3rd party lib [xEditable](https://vitalets.github.io/x-editable/) and control options are limited.
The alternative would be some "save"/"cancel" buttons that control the field (which I don´t really like):

![du2nSNE](https://user-images.githubusercontent.com/9299033/57012987-6e25fe80-6c09-11e9-9ff3-63a4bb9eb457.png)

The current behavior is that any "click" (or "mouseup") outside the "popover" saves the current value and closes it.
The current value is already pre-selected after double click a system for renaming. So simple `ctrl`+`c` can be used to copy the name instead of drag&drop the selection.
