### ISSUE TITLE
Error SSO

### ISSUE THREAD

**Issue by Alf-Life** [exodus4d/pathfinder#788]
Hello,

I have this error when closing the browser and the tracker does not work anymore  !!!
i made 1.5.1 update yesterday

![Capture3](https://user-images.githubusercontent.com/33965658/58284119-3e05f180-7daa-11e9-8d65-61d00e116924.PNG)

**Comment by tralafiti** [comment]
ESI scopes changed with the 1.5.1 update. Did you add the `esi-clones.read_clones.v1` to your application under https://developers.eveonline.com ?

**Comment by Alf-Life** [comment]
Yes i have it, this an update from 1.4.3 to 1.5.1, and he isn't tracking player !

**Comment by exodus4d** [comment]
@Alf-Life do you have some more information about your issue for us please?
- Anything "special" about your installation? - e.g. WebSocket installation?
- Anything "red" on the `/setup` page?
- Do you have the current `eve_universe` dump in your `eve_universe` DB?
- Have you double checked your *.ini files and compared them with the default settings? and/or added missing (new) options?

**Comment by Alf-Life** [comment]
hello,

this is an install on debian with nginx server.

i have one line in red

and eve universe db is automatically update ?

![patherror](https://user-images.githubusercontent.com/33965658/58819212-06136f80-8630-11e9-8b4e-fd798db8e67e.PNG)

**Comment by exodus4d** [comment]
The line in red is OK, its fine to have it empty if don´t have a "sub-dir" installation.

after creating the eve_universe DB you have to import the SQL dump file. read this: https://github.com/exodus4d/pathfinder/wiki/Database#3-import-initial-eve_universesql-db-dump

You can drop the eve_universe DB at any time and re-create it from scratch from `/setup` page and import the current SQL dump file. All maps/characters/.... will be still there, because all Pathfinder related stuff is stored in the `pathfinder` DB
