### ISSUE TITLE
Wrong calculation of the connection's remaining mass

### ISSUE THREAD

**Issue by v1nt06** [exodus4d/pathfinder#789]
![chrome_2019-05-26_13-49-21](https://user-images.githubusercontent.com/2842503/58380827-ba711e00-7fbe-11e9-9af9-75d6a62fd685.png)
Mass left in connection info is 1 299 058 t.
Actual value of the remaining mass is 1 397 458‬ t.

Steps to reproduce:
1. Find fresh wormhole.
2. Jump through it.
3. Add new jump to connection with the actual and non-standard mass of the ship.
4. Delete jump from the connection which was added automatically by the pathfinder.

**Comment by exodus4d** [comment]
Hi @v1nt06 , you are wrong, it is not a bug it is a feature:

- You see the total recorded mass after editing the table/adding records is **602 542t**, in footer of the second table. This is always the same number as **Logged mapp** row in **first** table.
- There is also an orange **Ship mass** row below, this represents your **current active** ship (where you are sitting in) and has **nothing** to do with the recorded masses from the 2nd table.
- The **Mass left** row shows you the estimated remaining mass of that wormhole **after you would have** jumped through it **the next time**. - So **Mass left** does **not** show the **current** remaining mass of the hole, it shows you the left mass after your next jump.

This behavior can be **toggled** by the little icon, then you get *1 397 458‬t*:

![info_mass_calc](https://user-images.githubusercontent.com/9299033/58765633-57125d80-8575-11e9-830b-b624b7f28c57.gif)

Since _Pathfinder_ does not know that your actual ship mass is 300 000t instead of 98 400t, the **default** ship mass is used for the **orange** row.  This feature is useful to check if the next jump would collapse the hole or not....

**Comment by v1nt06** [comment]
Hi @exodus4d,

Thanks for the explanation.
