### ISSUE TITLE
Can't access /admin

### ISSUE THREAD

**Issue by sharkbit** [exodus4d/pathfinder#796]
I Installed version 1.5.0 a few months ago and never tried admin because everything else worked great.  I want to upgrade to 1.5.1 and I get server 500...

PHP Fatal error:  Declaration of Controller\\Admin::getLogger($type = 'ADMIN') must be compatible with Controller\\Controller::getLogger($type = 'DEBUG'): Log in /var/www/pathfinder/app/main/controller/admin.php on line 19

**Comment by sharkbit** [comment]
So the better question is how to upgrade without a re-install?

**Comment by exodus4d** [comment]
@sharkbit The `PHP` error will be fixed in `1.5.2` (next week) thanks for reporting. 

If you are just 1 version behind, you can find an upgrade guide right at the [releases](https://github.com/exodus4d/pathfinder/releases) page. If you version is further behind, it depends...
Best practice:
1. `git pull` `master` branch on your server to update _Pathfinder_
2. `composer install` all (updated) 3rd party packages
3. visit `/setup` URL and look for "warnings"
  1. update your DB structure from `/setup` page
  2. look for other orange warnings on that page
  3. clear the cache dir  (default: /tmp/cache ) dir
4. done

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*
