### ISSUE TITLE
[Suggestion] Change key bindings to be set in configs

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#811]
Hey

It would nice if key bindings could be changed in configs, this way it's up to each host what key bindings is used for what.

**Comment by exodus4d** [comment]
I don´t see this to be implemented at the time. The problem is, that most of the key combos already have a default browser specific action, and preventing the default action can be difficult to achieve in all cases.

If someone really needs to change the keys, they can adjust them here https://github.com/exodus4d/pathfinder/blob/master/js/app/key.js#L6 and rebuild the JS files. Changes will automatically be shown in the "shortcuts" dialog.
