### ISSUE TITLE
[Enhancement Request] Preserve signatures after system deletion for the system

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#814]
Our group has run into this at least a dozen times in the past couple of weeks: 

We roll our chain and delete the old systems. We then re-encounter a system we had scanned down. All of its signatures are gone in PF, but in-game they all still exist. Can we preserve the signatures for at least 72 hours for a system after the system is deleted?

**Comment by exodus4d** [comment]
### New map setting option for "_Persistent system signatures_"
There is new checkbox in the "map settings" dialog to toggle this feature (default: **enabled**).
It behaves like the existing "_Persistent system alias_" checkbox next to it:
- On _delete_, system is now flagged with `active = 0`, rather than removed from the DB, in case "_Persistent system signatures_" is set for the map and signature data exists.
- On system _re-add_, `active` flag changed back to `1` and previous signature data is loaded.

![HAP9IlD](https://user-images.githubusercontent.com/9299033/61575884-290bbd00-aad2-11e9-8d84-68a8d469d236.png)

Signature data for `active = 0` systems gets removed by _cronjob_, if it was not updated for **3 days**.

There is also a new signature **counter** added to the "_add system_" dialog.

![1zeMObK](https://user-images.githubusercontent.com/9299033/61575883-24df9f80-aad2-11e9-84d5-8b998e484176.png)
