### ISSUE TITLE
Empty system shows the box where character should be [1.5.2]

### ISSUE THREAD

**Issue by mrurb** [exodus4d/pathfinder#823]
There is currently no one in this system and pathfinder is showing that fine, but the extra part is still showing under.
![image](https://user-images.githubusercontent.com/3414748/61730844-8aee5000-ad7a-11e9-84cb-3e360c936cad.png)
 
and when holding the mouse over the system to show everyone in that system it looks like this 
![image](https://user-images.githubusercontent.com/3414748/61730915-ab1e0f00-ad7a-11e9-90c3-fb75faf79d8d.png)

Testing done on the public pathfinder, i've not found the exact way to reproduce this yet. 

I did some further testing and it seems that if you are the last one to leave a system this problem is always there, in the case underneath i just moved a char from the C6 to the C5 and the only char tracked by this map is the char you can see on the map.
![image](https://user-images.githubusercontent.com/3414748/61737318-3baf1c00-ad88-11e9-882a-8d1d15adeb5d.png)

**Comment by mrurb** [comment]
It seems like that after the quick fix in #822 it now does not decrease the count of people in the system your leaving, after a bit of jumping around i got my map to look like this:
![image](https://user-images.githubusercontent.com/3414748/61737777-34d4d900-ad89-11e9-9ac6-3586f9172883.png)

From what i can see, it never actually counts down when a person leaves the system.

**Comment by exodus4d** [comment]
@mrurb Thanks! try the updated file once more, please. I missed something in the hurry

**Comment by mrurb** [comment]
@exodus4d tried the new map.php file and the problem does not seem to be fixed

**Comment by Meganitrospeed** [comment]
Can confirm, its not fixed, we are experiencing the same issue

**Comment by exodus4d** [comment]
@mrurb Thanks for your comprehensive testing and reporting! This is fixed with 3e269bddd.

#### Bug description:
To speed up client side map updates with **new** active characters data in a systems, unique **string hashes**, build from **current** active characters+ships, are compared with hashes build from **new** active characters data.
The `hash()` function was changed to build **integer hashes**, rather than **strings**...
https://github.com/exodus4d/pathfinder/commit/3e269bdddc4a774fb2c137fc9fa9e0de02e52d28#diff-630f9aae23d2da6473a482c15e3f6246L228
... this results in an error because e.g `45635.length` is `undefined`...
https://github.com/exodus4d/pathfinder/commit/3e269bdddc4a774fb2c137fc9fa9e0de02e52d28#diff-630f9aae23d2da6473a482c15e3f6246L315
... so system body becomes cleared but not collapsed.

#### There will be a new **Hotfix release** `v1.5.3` available, today
