### ISSUE TITLE
Tracking on multiple maps

### ISSUE THREAD

**Issue by infinity223** [exodus4d/pathfinder#827]
After I did an upgrade from 1.5.1 to 1.5.2 -> 1.5.3, a corp that is using it noticed that their position in tracked through all maps they are in (for example on 5). No matter what map is active, they got location, connections, etc. They say it didnt on 1.5.1.

**Comment by infinity223** [comment]
A simple example:

Im in WH XXX, which is added on both maps. I have two maps A and B. I'm on map A, as this is my active one, and I jump wh to system YYY. It is added on map A only, I go back to wh XXX. After a minute I switch map to B and suddenly system YYY is adding itself to map, often with default pos (left upper corner) and connection to system XXX as well.

**Comment by exodus4d** [comment]
@infinity223 sorry for the late response!

I just checked the code and was able to reproduce your example. 
First of all it looks strange to me as well and I expected a bug.
After I read all the commit messages of relevant code segments I realized that this was the intended behavior. I´m open for suggestions.

#### Hot it works
The log (jump) history of a character is independent from the current active map. Every time a char jumps into another system/switches ship/docks, a new "_log history_" is created.
The current active map now takes all the "_log history_" entries and checks if there are any _relevant/new_ changes and might create a new system based on those entries. Then entries get flagged as "checked" by this map and will not be checked the next update cycle. (Otherwise the prev. system would be added again, if someone manually deletes it.
If map switched, the new active map does the same and checks all the "_log history_" entries. (They are not flagged as "checked" by the new active map.

**Comment by infinity223** [comment]
My suggestion here is adding a "argument" to log history, that says on what map did it happen, and when map is checking newest log history it checks also this argument (if arg is an id of map = make it happen).

It will help a lot.

**Comment by exodus4d** [comment]
@infinity223 Yeah, I think this sounds reasonable, If a "_log history_" entry is already _checked_ by any other map, it will not be checked by other maps.
The only downside I could think of is, when you **forgot** to switch to the _correct_ map **before** jumping into a system. The **new** system would still be added to the wrong (current active) map and you have to **manually add** the system to the new map.

**Comment by AmraNiYesta** [comment]
I noticed this issue and i tried to manually delete the system i was in. I noticed this problem when I was on an alliance map and I was working on a personnal map. Each time i deleted manually the system, I reappear. Maps has to be indipendant.

**Comment by eophten** [comment]
> The only downside I could think of is, when you forgot to switch to the correct map before jumping into a system. The new system would still be added to the wrong (current active) map and you have to manually add the system to the new map.

What is the expected behavior in v1.5.5? I do think that the above is an extremely valid concern. similar to #886 , I would think that a great option to have is to have a type of map which is based around a "root" system (home system in most cases, or a farm hole, etc.) and scan the entire log history, regardless if it has been checked by another map, and add it to a map if an existing path to the map's defined root already exists.

**Comment by porowns** [comment]
Still have the very annoying behavior of systems being added when you're simply looking at another map but are in a different chain.
