### ISSUE TITLE
Offline pilots still show up

### ISSUE THREAD

**Issue by der-micky** [exodus4d/pathfinder#830]
Hi,

had an issue with 1.5.0. where offline still show up even after days/weeks. Today I updated to 1.5.3 and the problem remains.
As far as I understood the online pilot list is maintained by a cron job. In one of the issue posts you suggested a 

php index.php "/cron/deleteLogData"

with addidtional debug data. But that function crashes unmodified with a 500:

```
mk@seat:/var/www/pathfinder/pathfinder$ php index.php "/cron/deleteLogData"
Call to undefined method Cron\CharacterUpdate::isOnline() [/var/www/pathfinder/pathfinder/app/main/cron/characterupdate.php:68]
[app/lib/cron.php:129] Cron\CharacterUpdate->deleteLogData()
[app/lib/cron.php:162] Cron->execute()
[index.php:20] Base->run()
[10:37:00] ───────────────────────────
  type:     error
  code:     500
  status:   Call to undefined method Cron\CharacterUpdate::isOnline() [/var/www/pathfinder/pathfinder/app/main/cron/characterupdate.php:68]
  message:  Internal Server Error

```

Any hints ? 

Thank you and keep rolling this - Pathfinder rocks !!!

-Micky

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*
