### ISSUE TITLE
Manually updating signature causes the first signature data to reset and cannot update any other signatures

### ISSUE THREAD

**Issue by eboaen** [exodus4d/pathfinder#831]
New in 1.5.3

Steps to reproduce:

1.) Jump into any system
2.) Scan down and copy paste a few signatures with full data in them
3.) Manually change the type data in one of the signatures (except for the first signature in the list).  I tested with a Wormhole signature.
4.) This will reset the "type" data of the signature that is first in the list for that system.
5.) If you try to "fix" the issue and change the "type" of the first signature, you will get a "spinning wheel" and an odd ASCII character in the "type" field of the signature.
6.) You cannot update any signature at this point until you reload the browser.

**Comment by CalMatar** [comment]
I have been having similar issues and can expound on this issue. 
If you have a signature that you do not have any information past the ID, as indicated any signature but the first one on the list, and you go to update the Group it changes the first signature in the list. I have Print Screens to add to show the progress of the action.
Further, when you use the Undo button it not only resets what you just did but it also wipes out the LEADS TO information on all of the wormhole connections no matter how long ago you added them. 
This gets a little cumbersome when you have multiple connections you are tracking and you have to remember which connection is for which wormhole. 
The progression of this issue is that I created a signature out of whole cloth just for testing this issue with no information except the signature.
I attempted to change the Group to a Wormhole.
I then undid the changes.
The first screenshot shows the original list.
The second screenshot shows what happened after I set it as a wormhole.
The third screenshot shows the undo.
![Screenshot_78](https://user-images.githubusercontent.com/42744905/62399741-de1a8c80-b54a-11e9-82ef-1422dc9a1c42.png)
![Screenshot_79](https://user-images.githubusercontent.com/42744905/62399742-de1a8c80-b54a-11e9-9cbf-0fe21d2ca3fb.png)
![Screenshot_80](https://user-images.githubusercontent.com/42744905/62399743-deb32300-b54a-11e9-93a2-71d286a60c3c.png)
![Screenshot_81](https://user-images.githubusercontent.com/42744905/62399744-deb32300-b54a-11e9-84d4-211643a4dce9.png)




The fourth screenshot is the results of the undo.

**Comment by exodus4d** [comment]
@eboaen Thanks for reporting!

I could reproduce this issue and fixed it. 

### Root cause:
_Pathfinder_ [`v1.5.2`](https://github.com/exodus4d/pathfinder/releases/tag/v1.5.2) contain an upgraded for [_DataTables_](https://datatables.net/) _js_ lib `v1.10.12` → `v1.10.18`. 
In [`1.10.13`](https://cdn.datatables.net/1.10.13/) a bug was fixed regarding broken _selectors_:
> Row selector would incorrectly select rows if row index 0 was passed in with a selector modifier.
hg

***

@CalMatar 
The "undo" options represent a **full table data** _dump_ of the previous table state (all rows). This is required in case a user updates multiple signatures at once (e.g. from "signature reader"). There is just one new history data set stored that includes **all** prev. signatures. This explains **how** the "leads to" data is gone. 
I´ll check **why** it happen. This is of course not the intended behavior.

**Comment by CalMatar** [comment]
@eboaen , @exodus4d I just wanted to let you guys know a minor work around if you do run into this while you are doing things and you get stuck that does not involve the back option. You can refresh your browser tab and it will correct the issue as well without forcing you to log back in, most of the time.  Once in a while I have had to log back in but that is a rare occurrence so if you keep having this issue until it Pathfinder is updated that is what I suggest doing, or making sure you have the wormhole fully scanned before you past all the signatures into the signature box since you are going to scan it all anyway first.
Also, a neat trick I just found out I am not sure you are aware of. You do not need to open the paste box to actually paste into the signature or intel sections. You can simply click on the area and ctr+v to paste the info into the appropriate area. The only reason I open the box anymore is so I can do the lazy delete. Just an FYI.
