### ISSUE TITLE
Unable to resize map window

### ISSUE THREAD

**Issue by eophten** [exodus4d/pathfinder#855]
In chrome, using the resize (diagonal hamburger on the bottom right corner of the map window) fails to resize window. The user will visually see the cursor transition to the resize cursor (diagonal double arrow cursor) but will be unable to resize the window (size is unchanged on click and drag).

I have been unable to find reproduction steps or workarounds when it occurs (cleaning cookies/cache, login/logout, etc. are inconsistent at restoring proper function).

**Comment by november781** [comment]
workaround that I got to work was: switch active maps and then switch back.
Also make sure they are dragging STRAIT down, and angle will cause chrome to lose the drag-point.

**Comment by eophten** [comment]
> workaround that I got to work was: switch active maps and then switch back.

Unfortunately this fails. When I create and switch to a new map, the new map is adjustable and works as intended however the original map continues to fail on switch back.

**Comment by november781** [comment]
welp... it worked on chromium on linux... although it seems to be a timed think for chrome.... most of my members have found it working after waiting a while

**Comment by exodus4d** [comment]
Any chance to reproduce this? I could not do :(

**Comment by GabrielenT** [comment]
I have that happening too on my chrome browser, is there any fix for it yet?

**Comment by exodus4d** [comment]
@GabrielenT Nope, still unable to reproduce. If anyone gets that Issue, please open Chrome Dev-Tools, go to "Console" tab and check for any JS errors. - Post a screen with.
A JS stacktrace  would be nice as well.

**Comment by jasonmac73** [comment]
I am currently experiencing the issue with the map not expanding in Pathfinder.  Please see attached screenshot.  Let me know if you need something else.  
![pathfinder object](https://user-images.githubusercontent.com/19418404/67113094-541fae80-f19e-11e9-936d-87b28dc0b72e.JPG)

**Comment by exodus4d** [comment]
@jasonmac73 Thanks! No more information needed for now.
At a first glance it looks like a bug with "map access" tokens used by the WebSocket server to identify new subscribed clients. Those tokens have a limited expire time (few seconds). 
In case a client switches to an other map tab a new subscription request is send to the WebSocket server. In case those tokens were expired in the meanwhile, the subscription fails.

**Comment by Eve-Nayret** [comment]
I think the error in the above screenshot may be due to websockets not being enabled / working and a completely different issue. There are no error in the console when the resizing of the window stops working. 

I believe the issue may actually have something to do with the "Nearby" panel. When the issue is happening for me, if I drag the map height to be shorter than that panel, it will lock up and no longer allow for resizing. If I manually edit the active HTML and change the height of the main map panel to be longer, the issue goes away. 

I edited this height (it was actually initially 0):
![image](https://user-images.githubusercontent.com/52873836/67133464-e9409880-f1da-11e9-9967-27932d96f5b4.png)

This seems to be the panel I'm referring to that when the main panel height is smaller than this height, resizing stops:
![image](https://user-images.githubusercontent.com/52873836/67133598-87ccf980-f1db-11e9-9cd1-9e61b6704c4e.png)

I could be wrong though and it could be something else, but this appears to be at least a trigger and way to fix it temporarily. 

Stuck:
![image](https://user-images.githubusercontent.com/52873836/67133632-b77c0180-f1db-11e9-8add-392bd9b27532.png)

**Comment by exodus4d** [comment]
@Eve-Nayret Great work! 
The fix itself was a one liner: https://github.com/exodus4d/pathfinder/commit/0c9188634c7769f4011968380ca028e7ec6120fb#diff-b6116a1a68afbed92d1991e5a0dc0fc0R52

BTW. max visible pilots is now calculated dynamic based on the set map height:

![local](https://user-images.githubusercontent.com/9299033/67988548-9df1a580-fc30-11e9-9b03-4b1da0c99f02.gif)
