### ISSUE TITLE
[BUG] Static wormhole types showing undefined [v1.5.4]

### ISSUE THREAD

**Issue by eophten** [exodus4d/pathfinder#864]
Following upgrade to v1.5.4, static wormhole types are showing as undefined -> undefined

This is following the setup of new tables, fixing of tables, and clearing of cache.

![chrome_vsWwvikgcG](https://user-images.githubusercontent.com/7319297/66875431-e5f7a380-ef73-11e9-826a-69c5ad399464.png)

**Comment by eophten** [comment]
This appears like it may be related to the transition between v1.5.3 and v1.5.4. New systems added may not appear in an undefined state, still confirming.

**Comment by leesolway** [comment]
I had this issue, i did the following.. 

- Updated composer (just to make sure :D)
- Upgraded the eve_universe database as per the release notes
- Flushed the Redis cache
- Removed anything in cache directory
- Rebuild the system / static indexes in /admin

I am not sure if the steps are related or not, but hope it helps.

**Comment by exodus4d** [comment]
hi,

yeas getUniverseStatioData() is part of the  pathfinder_esi repository
which needs to be updated with Composer.  The function is new and it seems
to be that you don´t have updated the Composer packages.

You can remove the vendor/ dir and composer.lock file, and then run
"composer install" again.

Am Mi., 16. Okt. 2019 um 16:49 Uhr schrieb eophten <notifications@github.com

**Comment by eophten** [comment]
I have updated composer and the getUniverseStationData() error is no longer present. We are still seeing undefined static information for the home hole as well as no longer seeing a class type hint (H, L, N, C1-5) on the system bubble in map nor in the system information subwindow.

**Comment by exodus4d** [comment]
and you imported the new eve_universe.sql dump file?

Am Fr., 18. Okt. 2019 um 05:38 Uhr schrieb eophten <notifications@github.com

**Comment by eophten** [comment]
When setting up a new eve_universe database (create database, setup tables, fix columns) from /setup, i receive this error on fix columns action: Column not found: 1054 Unknown column 'factionId' in 'field list' [/opt/www/pathfinder/app/lib/db/sql.php:226]'. At this point, /setup becomes unavailable for any further access until i drop the schema and begin again.

![Error on Fix columns](https://user-images.githubusercontent.com/7319297/67115356-a1eae580-f1a3-11e9-9ccf-b09e25a0eeff.png)

**Comment by mrurb** [comment]
@eophten This is a cache problem, please clear redis

**Comment by exodus4d** [comment]
@mrurb Agree! MySQL table "Schema"s are cached for (I think 60s). This is OK because table structure does not change that often. 
If new columns/tables wer added/changed after an upgrade on `/setup` page, you schould **always** clear the cache (`/tmp/cache` dir or _Redis_ cache DB) - or _wait_ until cache data becomes invalid (60s)...

I thought about clearing **cached Schemas** automatic after DB update on `/setup` but it turns out to be a bit tricky... Retrieving the cache keys for delete is not possible (There is no _public_ method provided by the framework). So I build my own method that _rebuilds_ the key for delete... But for now this method is not used and still _on testing_:

https://github.com/exodus4d/pathfinder/blob/aef6d4e0246dfbe240063ca41b8daa016650139d/app/main/model/abstractmodel.php#L188-L198
