### ISSUE TITLE
[Bug] Group tooltip/dropdown window persistance

### ISSUE THREAD

**Issue by DukeSov** [exodus4d/pathfinder#865]
When manually changing the "group" of a signature with a filter applied, while the group is filtered out , the tooltip/dropdown window which shows changes being applied persists and does not go away. In order to get rid of the tooltip, the system you are viewing needs to be refreshed by clicking again on the system in the map.

I assume this is occurring because the "Signatures" window automatically jumps over to the "type" dropdown after specifying a "group", asking for the user to select the name of the type. Because the signature is automatically filtered out after specifying a group, wonky things start happening.

How to recreate the bug:
- Filter out one or more groups in the "Signatures" window
- Manually change the group to one of the options filtered out

Screenshots and gif of the bug in action:
_Signature "HGW" before group is changed_
![before](https://user-images.githubusercontent.com/37763780/66891342-1d7f4380-efa6-11e9-84ac-84ce8d381f89.png)
_Signature "HGW" after group is changed_
![after](https://user-images.githubusercontent.com/37763780/66891335-19ebbc80-efa6-11e9-8971-03aceb007a91.png)
_Window persiting after changing group of signature "HZE"_
_The tooltip goes away after I click the system in the map window_
![persistant](https://user-images.githubusercontent.com/37763780/66891348-2112ca80-efa6-11e9-80d4-343591d3d04b.gif)

**Comment by exodus4d** [comment]
### :heavy_check_mark: Issue resolved
This issue was resolved by the commit(s) and/or the comments above.
It will be *auto-closed* with the upcoming release ( **merge** into `master` branch). Please check the attached **Milestone** information.

Many thanks to all participants/contributors for the helpful comments! :+1:

#### :information_source: You may reopen this issue if it has been closed in error.

***
*Auto-generated response*
