### ISSUE TITLE
[Enhancement ] Dotted lines around "Unknown" when frigate connection

### ISSUE THREAD

**Issue by porowns** [exodus4d/pathfinder#874]
Now that we have frigate connections properly denoted under "Types" for wormholes, it'd be nice to display the dotted line for frigate holes around "Unknown" destination. 

This serves as intel as to why that connection wasn't mapped, and someone can bring the right ship to map it.

**Comment by exodus4d** [comment]
@porowns I´m not sure what exactly you mean?
Do you mean the **dotted** lines (top/bottom) in the "leads to" sig. table column ?

So in this example the frig wh **L005** signature is mapped to the **C2** but not linked in the sig. table. And you want the dotted borders around the **_unknown_** "leads to" cell?

![frig_wh_question](https://user-images.githubusercontent.com/9299033/68527751-de18ee00-02ea-11ea-860c-e2332de9d7b3.png)

**Comment by porowns** [comment]
Yeah, I think it'd be useful for explaining why some signatures aren't mapped (e.g someone needs an astero)

**Comment by exodus4d** [comment]
After checking the existing code base, it turned out to be more complex than expected. 
I had to implement this a bit different:

##### The "type" column now shows the "size" ('S', 'M', 'L', 'XL') label.
![frig_wh_question2](https://user-images.githubusercontent.com/9299033/68997045-4abf5a00-08a2-11ea-9f67-2174b8d9e149.png)
