### ISSUE TITLE
Shattered Wormhole Sig and Anom list wrong

### ISSUE THREAD

**Issue by jbs1** [exodus4d/pathfinder#875]
Ok so after doing some further, it seems that the sites i thought were missing are actually in the signature_type.js file.
However it seems pathfinder does not take into account the unique nature of shattered wormholes.

Shattered wormholes can "generate signatures and anomalies of their own class, and of one class higher or lower."

Eg. in my particular case I was scanning the J003789 shattered WH.
That is a C3, so pathfinder only let's me select c3 sites. However I found the C4 sites "Forgotten Frontier Evacuation Center" and "Unsecured Frontier Digital Nexus" in there but couldn't select them from the dropdown menu.

So pathfinder needs a special case for the shattered holes to take into account this uniqueness.

**Comment by CalMatar** [comment]
Yes, you are correct in this. I forget what the C13 and C6 have for the below and above signatures though as they are the lowest and highest shattered holes respectively. I can't remember if they have anything in that direction since there is actually nothing that is below or above those WHs. As for the C2,C3,C4, and C5 Worm Holes they will always have signatures for one level above and one level below in ALL signatures whether it be combat, ore, gas, data, or relic. I believe that this also pertains to the Drifter holes as well since they are, in essence, shattered Worm Holes of a certain class that just happen to be Drifter holes that are connected to K-Space.

**Comment by exodus4d** [comment]
@jbs1 Thanks for your report! This information was new to me.
@CalMatar Thanks for your explanation!

For now  I implemented the following for C1-C6 Stattered WHs. 
If someone can verify how C13s or Drifter holes (C14-C18) behave (e.g. screens from the EVE client), I will add them, too.

Source: [https://wiki.eveuniversity.org/Shattered_wormhole_systems](https://wiki.eveuniversity.org/Shattered_wormhole_systems#Standard_Shattered_Wormhole_Systems)
#### Changes:
- Signature '**type**' select options in **Shattered** C1,-2,-3,-4,-5,-6 holes now includes the types from one class higher or lower, too.
  - e.g. **C1** Shattered has available signature type options vor: **C1**, C2
  - e.g. **C4** Shattered has available signature type options vor: C3, **C4**, C5
  - e.g. **C6** Shattered has available signature type options vor: C5, **C6**
- This only affects signatures with '**group**':  **Combat**, **Relic**, **Data**, **Gas** or **Ore**

In your example, **Shattered J003789 C3** has **Relic** options from **C2, C3, C4**. (hint: C2, C3 can also have all Relic sites from 0.0):

![NPUl6fm](https://user-images.githubusercontent.com/9299033/69907627-38800880-13d8-11ea-8e50-2999dff33c8d.png)

**Comment by jbs1** [comment]
so, something more inconsistencies happened.
I just scanned a C2 shattered called J001057 and there i found an "Instrumental Core Reservoir" which is a C5/C6 site. So it seems that it is not just as straightforward as +/- 1 class.
I will try to investigate that further.
https://i.imgur.com/IdbOTFk.png

**Comment by jbs1** [comment]
ok, after some more checking it seems specifically for gas sigs all types of gas sigs spawn in all classes of shattered wormholes.

**Comment by CalMatar** [comment]
Yes, you are correct. I did make a mistake on adding the gas into that list, as well as ore for that matter. Both of those will show up in all classes of wormholes regardless of what the type of site with the exception of the shattered specific ice and shattered depris field. Otherwise all gas and all ore fields will be in all wormholes. Sorry for the confusion.

**Comment by exodus4d** [comment]
rgr, Ill make all Gas and Ore sites from all WHs (C1-C6) available in all Shattered WHs (C1-C6, C13).

@CalMatar 
>  shattered specific ice and shattered depris field
Do you have a source URL with that information, too?

**Comment by exodus4d** [comment]
I re-structured [signature_type.js](https://github.com/exodus4d/pathfinder/blob/develop/js/app/conf/signature_type.js). It should be more readable now, and separating the different groups of sites enables me to mix up any combination we we figured out by adding a "special" case to that function:
https://github.com/exodus4d/pathfinder/blob/2f7807f326e192f5764effa156f0555e63f80dcc/js/app/ui/module/system_signature.js#L241-L253

**Comment by CalMatar** [comment]
Sorry for another mistake but it actually called a Shattered Debris Field. I misspelled it by mistake.

**Comment by exodus4d** [comment]
@CalMatar I added the **two** new "**Ore**" sites, to **all Shattered** C1-C6 and C13 WHs:
- Shattered Debris Field
- Shattered Ice Field
