### ISSUE TITLE
Unable to change Max_system values for pre-existing maps

### ISSUE THREAD

**Issue by november781** [exodus4d/pathfinder#878]
I have in my pathfinder.ini
```[PATHFINDER.MAP.PRIVATE]
LIFETIME                        =   99999
MAX_COUNT                       =   3
MAX_SHARED                      =   10
MAX_SYSTEMS                     =   100
LOG_ACTIVITY_ENABLED            =   1
LOG_HISTORY_ENABLED             =   1
SEND_HISTORY_SLACK_ENABLED      =   0
SEND_RALLY_SLACK_ENABLED        =   1
SEND_HISTORY_DISCORD_ENABLED    =   0
SEND_RALLY_DISCORD_ENABLED      =   1
SEND_RALLY_Mail_ENABLED         =   0
```

However, I still cannot add over 50 systems in my private map. All other overwrites seem to work except for this one.

**Comment by november781** [comment]
None of the MAX_SYSTEMS overwrites take, not even the corp one

**Comment by november781** [comment]
Edit: just does not take for current maps.

**Comment by november781** [comment]
Attach to this, cannot increase the value to over 100

**Comment by CalMatar** [comment]
I BELIEVE there is a fix for this already in the works from #847, but I might be wrong. That ticket pertains to shattered Drifters holes with upwards of 100 signatures and is being worked on at the moment so will probably take care of this issue as well but I am not 100% sure of that.

**Comment by november781** [comment]
looks like it had to purge cache before the new maximum was set, I'm gonna close this issue now....

**Comment by exodus4d** [comment]
Yeah they are cached for 1h by the server. Some frequently accessed values from *.ini files are cached, otherwise *.ini files would be parsed on every request.
Even though "map limits" are validated in PHP, they are also send to the clients for client side validation if e.g. a new system should be added... There is also an HTTP cache header send to the clients. -> If you clean the server cache, clients might have the old limits cached for <=1h. With active browser dev-tools and disabled response caching you should get the new values asap (for testing).
