### ISSUE TITLE
System links 

### ISSUE THREAD

**Issue by Sabistik** [exodus4d/pathfinder#888]
Hi, im just after update to 1.5.5 and i dont see system links to dotlan etc.
They are moved again to another place or it is a bug?
![pf_links](https://user-images.githubusercontent.com/2961411/70850565-0ff21700-1e8c-11ea-9759-5b3b22c82991.png)

**Comment by CalMatar** [comment]
That is not where the links are, nor have been since 1.5.3. They were moved in 1.5.4. This is where they are on the public Pathfinder on 1.5.5 as of 12/15/19:
![PathfinderSysLinks](https://user-images.githubusercontent.com/42744905/70865269-72e5bb80-1f29-11ea-98a5-79a103ca1105.png)
Everything is working the way it should.

**Comment by Sabistik** [comment]
hm. so why i dont see them after update to 1.5.5?  i made the update as i can reed on https://github.com/exodus4d/pathfinder/releases/tag/v1.5.5 

```
# git status
On branch master
Your branch is up-to-date with 'origin/master'.
```

**Comment by Sabistik** [comment]
It was browser cache...
