### ISSUE TITLE
Cronjob not working?

### ISSUE THREAD

**Issue by VyndarielAriami** [exodus4d/pathfinder#892]
Hey,

I newly installed Pathfinder 1.5.4 and updated to 1.5.5.

However, it does seem that I cannot get the cronjob running

crontab -e (user root)
* * * * * cd /var/www/DOMAIN/public; sudo -u www-data php index.php / cron >> /var/www/DOMAIN/logs 2>&1

Based on the wiki I should be able to visit https://www.pathfinder-w.space/cron

If I visit https://DOMAIN/cron I get the 404 error page (like the one in the wiki).

Based on the logs I do not see a execution in /logs/cron.log 

can someone point me to the correct direction, please?

Best

**Comment by zap2zero** [comment]
Did you make sure you have
`web = TRUE`
in app/cron.ini? Maybe the default changed from 1.5.4 to 1.5.5?

**Comment by VyndarielAriami** [comment]
Hi zap,

that worked for the URL

however, the cron doesnt run automatically if I keep it set to FALSE (didnt checked if it works if I set it to TRUE)

does web needs to be TRUE for the cron to be working?

**Comment by zap2zero** [comment]
Check the documentation - enabling the cronjobs via web does not automatically run them, as documented in the [wiki](https://github.com/exodus4d/pathfinder/wiki/Cronjob).
You have to set the flag to true and then use a cron-service to trigger your cron-url every minute.

**Comment by VyndarielAriami** [comment]
Hi Zap,

I get that, however, the root cronjobs (as written in first post) arent run either.

**Comment by zap2zero** [comment]
I dont have any issue with running my cronjob via the web API.

Isnt the local cronjob to be like "php index.php /cron" (no space between / and cron)?

**Comment by november781** [comment]
I'm having a similar issue with getting cron to run the jobs. The jobs execute fine from the ui in /setup but will not execute automatically and I get no error or success logs

**Comment by november781** [comment]
@VyndarielAriami I got mine to work, make sure that you have the cron job outputting to a file that the user running the job has access to.

IE. I output to /var/log/cron-www/pathfinder.ini I needed to make sure that the /var/cron-www/ folder existed and was owned by my cron user, root in my case.

My issues was because that folder did not exist so the job was failing. If your cron user can't write to the file or folder it will likely fail.

**Comment by exodus4d** [comment]
As @VyndarielAriami said, it is important that the user who runs the cronjob is the same who runs your Webserver. This is relevant because Cache files are written to disc into PF´s  cache dir `tmp/cache/`. The cronjob user also tries to read/write files from it, so he needs access to it. If you want to run the cronjob with any other user, you need to make sure he has access. 
The other problem would be, if files are written by the cronjob user, they must be accessible by the webservers user, too.

`crontab -e` example:
```
# Pathfinder DEVELOP
# * * * * * cd /var/www/dev.pathfinder-w.space/public_html; sudo -u nginx php index.php /cron >> /var/log/cron-www/dev.pathfinder.log 2>&1
```

`vi /etc/php-fpm.d/www.conf` example:
```
listen.owner = nginx
listen.group = nginx
```
`vi /etc/nginx/nginx.conf` example
```
user nginx nginx;
```
