### ISSUE TITLE
map wont open / work ingame

### ISSUE THREAD

**Issue by rohimma** [exodus4d/pathfinder#90]
like the title says.. ingame is broken..

**Comment by lunedis** [comment]
Same here.

**Comment by Bingmano** [comment]
Same.  No updates have been made on any forums :(

**Comment by exodus4d** [comment]
I'm on it sorry. Expect a fix tomorrow. Im currently not at home.

Bingmano <notifications@github.com> schrieb am Di., 2. Feb. 2016 17:47:

**Comment by Bingmano** [comment]
awesome! not really concerned about timeframe (i want to deploy on my own environment eventually) i wanted to test it out to see if it is something I can force my corp to use :).  I really love the design, awesome work!

**Comment by exodus4d** [comment]
So Bug is fixed. I have just tested it on SISI.

The problem was an upgrade of a third party Javascript Plugin. I have downgraded the plugin to its previous version. This was just a problem with the IGB which unfortunetely does not support newer *ECMAScript 5* notations. 

Feel free to test it. Sorry for this :(

**Comment by Bingmano** [comment]
You are a prince among men.  Tested in Prod and works!  Gotta love those outdated IGB plugins....Is there any chance the documentation will be updated soon to deploy on a private server?

**Comment by sn0opy** [comment]
Could you push the code to Git please? I switched back to an older `mappage.js` which did the trick for me.

@Bingmano: what exactly do you mean? The [Wiki](https://github.com/exodus4d/pathfinder/wiki) explains that already

**Comment by phneak** [comment]
Which commit did you checkout to get IGB map working?  I have tried a couple and none seem to get me working

**Comment by exodus4d** [comment]
It is not on Guthub yet.  I'm still on a business trip in NL. Will update
die repo this weekend when im back in Ger.

phneak <notifications@github.com> schrieb am Fr., 5. Feb. 2016 15:04:

**Comment by phneak** [comment]
I figured it out - did a full pull of older commit and got it working

**Comment by jalavoy** [comment]
Just to save people some searching, I had to revert back to commit 3f4d33a3a9d3f55db30ae2ea841a616876ff8eac to get around this problem.

**Comment by exodus4d** [comment]
GitHub is now back in sync with my "official" Installation https://www.pathfinder-w.space

`v1.0.0RC2` is released and includes the the fix for this Issue.  
I forgot testing the IGB after upgrading [jsPlumb](https://jsplumbtoolkit.com/) from `v1.7.6` -> to `v2.0.5` in `v1.0.0RC1` (shame on me)

But is shows once more that the IGB does not have any future. 
If the CREST implementation (#84) is finally done, there is no need to support the IGB any longer. But i will support the IGB until CCP removes it (which will hopefully not take to long)

Sorry for all the hassle! Feel free to report any bugs!
