### ISSUE TITLE
Wormhole Info Tab Not Poplulating

### ISSUE THREAD

**Issue by EveZeroEight** [exodus4d/pathfinder#939]
Hi,

Ever since 2.0 my Wormhole Information Tab does not populate with information like the system's statics. Also I am unable to use the edit function and add a note. Below is a picture of what's happening.

![chrome_jEGNgQM8dv](https://user-images.githubusercontent.com/63268051/78732146-2c5b1780-7985-11ea-8a29-6162c95aae2e.png)

**Comment by thethufir** [comment]
It happens for me too, and other people in our alliance. Some people don't seem to have the issue. And someone also said they made it come back after clearing cookies. I tried that myself without luck though.

I'm using Chrome btw.

**Comment by exodus4d** [comment]
Interesting, I have never seen this. Could you please open your browser dev-tools (F12), with to "console" tab, then click at the system that does not show data, and watch for errors. If you get anything, link a screenshot here,

**Comment by thethufir** [comment]
It's quite interesting. After a couple of days, the issue stopped being there, and it now works as intended. Same story from my other corpmates. Could it have something to do with old cache, cookies or something? Maybe an artifact from importing our map from the previous version? I would provide you with the console data, but since the issue is fixed for me now, i don't think it's gonna be of much value. Let me know if you think otherwise.

**Comment by exodus4d** [comment]
It is hard to say where it might come from without further information. :( If you see this again, try to collect as many info from the console as you can. Other information might also be relevant:
- Browser/version
- OS
- time

Feel free to re-open if you got any information.

**Comment by Valiantiam** [comment]
Im also having this problem now. Some users have the issue, other doe not. Here is what my browser log says:

● Client syncStatus: ajax. initMapWorker() rejected by command: Invalid mapAccessData! payload: Object
system_info.js:210 Uncaught TypeError: Cannot read property 'innerHTML' of null
    at system_info.js:210
    at Object.execCb (require.js:29)
    at b.check (require.js:18)
    at b.<anonymous> (require.js:22)
    at require.js:7
    at require.js:23
    at y (require.js:6)
    at b.emit (require.js:23)
    at b.check (require.js:19)
    at b.enable (require.js:23)

***Edit for more info***
Chrome | Version 83.0.4103.97 (Official Build) (64-bit)
Windows 10

Happening immediately after having upgraded to 2.0.0. I did try clearing all cache using the /setup dashboard

The issue does not exist if I use Firefox apparently. I did try clearing cache and cookies for chrome as well and that didnt change it.

**Comment by tralafiti** [comment]
Seen similar problems in our corp. Seems to be caused by caching of the html-templates - e.g. public/templates/modules/system_info.html etc.. Whenever the template changes you have to kill your browser cache at the moment. Should be fixable by adjusting webserver configs or the js that fetches these templates
