### ISSUE TITLE
Character verification failed 

### ISSUE THREAD

**Issue by integral0** [exodus4d/pathfinder#959]
After pressing the Home button, the character icon does not appear, so that I can log in again without authorization. Cookies correspond to what is in the table.

https://i.imgur.com/AgAoHxu.gif

What am I doing wrong?

**Comment by exodus4d** [comment]
Hi @integral0 ,

the first login seems to work, expire date for login cookie and expire timestamp in DB were set.
I can not see anything going wrong by watching your record, You should do some more investigations:

Side note: CCP currently has some serious issues with UTF-8/16 decoding, and returned invalid JSON for "some" endpoints. This is a general issue, but might be the problem in your case: https://github.com/esi/esi-issues/issues/1194

### What happens:
When you go back to `/login` page, there are ajax requests send for each character login cookie (`/api/User/getCookieCharacter`), The request "re-validates" cookie data and if something "fails" (bad response), cookie gets deleted (from DB and browser):
How it should look like:
![image](https://user-images.githubusercontent.com/9299033/80276367-90e9d680-86e8-11ea-9d28-67e884c77f00.png)

### Please check:
- I guess you have already checked PHP´s error logs, if not please do.
- Set `DEBUG =   3` in `environment.ini`
- Before you go back to `/login`, open Chrome dev-tools go to "network" tab. After page load you will see the validation request `getCookieCharacte`. Select request, and check "preview" tab for the response (like my screen above). Is there any thing returned that points to an error (e.g. stack trace)?
- If request returns a HTTP 200 (good), and no errors in response, you need to either re-mote debug 2 methods with breakpoints, or go through the code step-by-step and print out some values to figure out what exactly the problem is:

### Debug steps:
- In `getCookieCharacter()` please check the values for `$cookieData` and `$characters`
https://github.com/exodus4d/pathfinder/blob/62dc991760e3d0bfde078affde20a3fcc6ed2360/app/Controller/Api/User.php#L126-L129
  add 2 `var_dump()` before the `if()` sections like:
  ```php
        var_dump($this->getCookieByName($cookieName));
        if( !empty($cookieData = $this->getCookieByName($cookieName) )){
            // cookie data is valid -> validate data against DB (security check!)
            // -> add characters WITHOUT permission to log in too!
            var_dump($this->getCookieCharacters(array_slice($cookieData, 0, 1, true), false));
            if( !empty($characters = $this->getCookieCharacters(array_slice($cookieData, 0, 1, true), false)) ){
  ```
  - Go back to `/login` page (with valid cookie data set) and check the response.
- I guess the `$this->getCookieCharacters(...` will not return anything.... Next step:
-  You need to go step by step through the code and check where it fails: https://github.com/exodus4d/pathfinder/blob/master/app/Controller/Controllerr.php#L303-L399

**Comment by integral0** [comment]
hmm, error

![](https://i.imgur.com/8obO3IM.png)

**Comment by exodus4d** [comment]
Sorry I was not done with writing before submit the last post. I´m done now, please read.

**Comment by integral0** [comment]
Found a reason.
One of the parameters was duplicated in CCP_ESI_SCOPES
Thank you!
